-- Seed: Spanish B1 vocabulary for Polish speakers
-- Table: vocabulary_words  (language = 'es', level = 'B1')
-- word_en holds the SPANISH word; translation_pl is the Polish translation.
-- Categories: emocje, edukacja, technologia, środowisko, relacje, media, kultura, zwroty codzienne
-- Idempotent: existing es/B1 rows are removed before re-inserting.

delete from vocabulary_words where language = 'es' and level = 'B1';

insert into vocabulary_words (language, level, category, word_en, translation_pl, example_sentence) values
-- emocje
('es', 'B1', 'emocje', 'alegría', 'radość', 'Sentí una gran alegría cuando aprobé el examen final.'),
('es', 'B1', 'emocje', 'tristeza', 'smutek', 'La tristeza que sintió tras la despedida duró varios días.'),
('es', 'B1', 'emocje', 'miedo', 'strach', 'Tengo miedo de hablar en público delante de tanta gente.'),
('es', 'B1', 'emocje', 'enfado', 'złość', 'Su enfado desapareció en cuanto le pedí perdón.'),
('es', 'B1', 'emocje', 'vergüenza', 'wstyd', 'Me da vergüenza cantar delante de mis compañeros.'),
('es', 'B1', 'emocje', 'orgullo', 'duma', 'Mis padres sienten mucho orgullo por mis logros.'),
('es', 'B1', 'emocje', 'celos', 'zazdrość', 'Los celos pueden destruir cualquier relación de pareja.'),
('es', 'B1', 'emocje', 'angustia', 'niepokój', 'La espera de los resultados me produjo una gran angustia.'),
('es', 'B1', 'emocje', 'emoción', 'wzruszenie', 'No pude ocultar la emoción al ver a mi familia.'),
('es', 'B1', 'emocje', 'felicidad', 'szczęście', 'La felicidad no depende solo del dinero que tengas.'),
('es', 'B1', 'emocje', 'ansiedad', 'lęk', 'La ansiedad antes de una entrevista es completamente normal.'),
('es', 'B1', 'emocje', 'cariño', 'czułość', 'Trata a sus abuelos con mucho cariño y paciencia.'),
('es', 'B1', 'emocje', 'rabia', 'wściekłość', 'Sentí rabia cuando descubrí que me habían mentido.'),
('es', 'B1', 'emocje', 'sorpresa', 'zaskoczenie', 'Su reacción fue una auténtica sorpresa para todos nosotros.'),
('es', 'B1', 'emocje', 'nostalgia', 'nostalgia', 'Siento nostalgia cuando escucho las canciones de mi infancia.'),
('es', 'B1', 'emocje', 'entusiasmo', 'entuzjazm', 'Los alumnos empezaron el curso con mucho entusiasmo.'),
('es', 'B1', 'emocje', 'decepción', 'rozczarowanie', 'Fue una gran decepción no conseguir el trabajo.'),
('es', 'B1', 'emocje', 'esperanza', 'nadzieja', 'Nunca pierdas la esperanza de cumplir tus sueños.'),
('es', 'B1', 'emocje', 'soledad', 'samotność', 'A veces la soledad ayuda a conocerse mejor a uno mismo.'),
('es', 'B1', 'emocje', 'ternura', 'tkliwość', 'Miraba al bebé con una ternura infinita.'),
('es', 'B1', 'emocje', 'asombro', 'zdumienie', 'Observó el paisaje con asombro y no dijo nada.'),
-- edukacja
('es', 'B1', 'edukacja', 'asignatura', 'przedmiot (szkolny)', 'Las matemáticas son mi asignatura favorita este año.'),
('es', 'B1', 'edukacja', 'aprobar', 'zdać (egzamin)', 'Estudié mucho para aprobar el examen de historia.'),
('es', 'B1', 'edukacja', 'suspender', 'oblać (egzamin)', 'Si no estudias, es probable que suspendas la asignatura.'),
('es', 'B1', 'edukacja', 'matrícula', 'rejestracja (na uczelni)', 'El plazo de matrícula termina la próxima semana.'),
('es', 'B1', 'edukacja', 'beca', 'stypendium', 'Consiguió una beca para estudiar en el extranjero.'),
('es', 'B1', 'edukacja', 'carrera', 'kierunek studiów', 'Estoy pensando en qué carrera universitaria elegir.'),
('es', 'B1', 'edukacja', 'licenciatura', 'licencjat (dyplom)', 'Terminó la licenciatura en Derecho con buenas notas.'),
('es', 'B1', 'edukacja', 'examen', 'egzamin', 'El examen final será el lunes por la mañana.'),
('es', 'B1', 'edukacja', 'apuntes', 'notatki', '¿Me puedes prestar tus apuntes de la clase de ayer?'),
('es', 'B1', 'edukacja', 'horario', 'plan zajęć', 'Mi horario de clases cambia cada semestre.'),
('es', 'B1', 'edukacja', 'profesorado', 'grono nauczycielskie', 'El profesorado del instituto es muy competente.'),
('es', 'B1', 'edukacja', 'aula', 'sala lekcyjna', 'El aula estaba llena de estudiantes esperando al profesor.'),
('es', 'B1', 'edukacja', 'deberes', 'zadanie domowe', 'Los niños tienen que terminar los deberes antes de cenar.'),
('es', 'B1', 'edukacja', 'asistencia', 'obecność', 'La asistencia a las clases es obligatoria en esta universidad.'),
('es', 'B1', 'edukacja', 'conocimiento', 'wiedza', 'La lectura amplía nuestro conocimiento del mundo.'),
('es', 'B1', 'edukacja', 'aprendizaje', 'uczenie się', 'El aprendizaje de un idioma requiere tiempo y práctica.'),
('es', 'B1', 'edukacja', 'enseñanza', 'nauczanie', 'La enseñanza pública debería recibir más recursos.'),
('es', 'B1', 'edukacja', 'título', 'dyplom (tytuł)', 'Necesitas un título universitario para ese puesto.'),
('es', 'B1', 'edukacja', 'resumen', 'streszczenie', 'El profesor nos pidió un resumen del libro.'),
('es', 'B1', 'edukacja', 'nota', 'ocena', 'Sacó una nota excelente en el examen de química.'),
('es', 'B1', 'edukacja', 'facultad', 'wydział', 'La facultad de Medicina está al lado del hospital.'),
-- technologia
('es', 'B1', 'technologia', 'ordenador', 'komputer', 'Mi ordenador es muy lento y necesito comprar otro.'),
('es', 'B1', 'technologia', 'pantalla', 'ekran', 'Pasar muchas horas frente a la pantalla cansa la vista.'),
('es', 'B1', 'technologia', 'teclado', 'klawiatura', 'Se me ha estropeado una tecla del teclado.'),
('es', 'B1', 'technologia', 'contraseña', 'hasło', 'Debes cambiar la contraseña cada pocos meses por seguridad.'),
('es', 'B1', 'technologia', 'archivo', 'plik', 'No encuentro el archivo que guardé ayer por la noche.'),
('es', 'B1', 'technologia', 'correo', 'poczta (e-mail)', 'Te he enviado los documentos por correo electrónico.'),
('es', 'B1', 'technologia', 'navegador', 'przeglądarka', 'Abre el navegador y busca la página de la empresa.'),
('es', 'B1', 'technologia', 'descargar', 'pobierać', 'Voy a descargar la aplicación en mi teléfono nuevo.'),
('es', 'B1', 'technologia', 'actualizar', 'aktualizować', 'Deberías actualizar el sistema para evitar problemas.'),
('es', 'B1', 'technologia', 'red', 'sieć', 'La red del hotel es demasiado lenta para trabajar.'),
('es', 'B1', 'technologia', 'usuario', 'użytkownik', 'Cada usuario tiene su propio nombre y contraseña.'),
('es', 'B1', 'technologia', 'dispositivo', 'urządzenie', 'Puedes conectar varios dispositivos a la misma cuenta.'),
('es', 'B1', 'technologia', 'aplicación', 'aplikacja', 'Esta aplicación me ayuda a organizar mis tareas diarias.'),
('es', 'B1', 'technologia', 'nube', 'chmura', 'Guardo todas mis fotos en la nube por seguridad.'),
('es', 'B1', 'technologia', 'programador', 'programista', 'Trabaja como programador en una empresa de tecnología.'),
('es', 'B1', 'technologia', 'enlace', 'link (odnośnik)', 'Haz clic en el enlace para leer la noticia completa.'),
('es', 'B1', 'technologia', 'copia de seguridad', 'kopia zapasowa', 'Haz una copia de seguridad antes de formatear el ordenador.'),
('es', 'B1', 'technologia', 'datos', 'dane', 'La empresa protege los datos personales de sus clientes.'),
('es', 'B1', 'technologia', 'carpeta', 'folder', 'Guarda todos los documentos en esta carpeta compartida.'),
('es', 'B1', 'technologia', 'inalámbrico', 'bezprzewodowy', 'Compré un ratón inalámbrico para trabajar más cómodo.'),
('es', 'B1', 'technologia', 'buscador', 'wyszukiwarka', 'Escribe la pregunta en el buscador y verás muchos resultados.'),
-- środowisko
('es', 'B1', 'środowisko', 'medio ambiente', 'środowisko naturalne', 'Debemos cuidar el medio ambiente para las futuras generaciones.'),
('es', 'B1', 'środowisko', 'contaminación', 'zanieczyszczenie', 'La contaminación del aire es un problema grave en las ciudades.'),
('es', 'B1', 'środowisko', 'reciclaje', 'recykling', 'El reciclaje de plástico ayuda a reducir la basura.'),
('es', 'B1', 'środowisko', 'residuos', 'odpady', 'La fábrica no puede tirar sus residuos al río.'),
('es', 'B1', 'środowisko', 'energía', 'energia', 'Cada vez usamos más energía procedente del sol.'),
('es', 'B1', 'środowisko', 'sostenible', 'zrównoważony', 'El turismo sostenible respeta la naturaleza y a la gente local.'),
('es', 'B1', 'środowisko', 'calentamiento', 'ocieplenie', 'El calentamiento global está derritiendo los polos.'),
('es', 'B1', 'środowisko', 'sequía', 'susza', 'La sequía de este verano ha afectado a los agricultores.'),
('es', 'B1', 'środowisko', 'inundación', 'powódź', 'La inundación destruyó muchas casas cerca del río.'),
('es', 'B1', 'środowisko', 'bosque', 'las', 'Pasear por el bosque en otoño es muy relajante.'),
('es', 'B1', 'środowisko', 'especie', 'gatunek', 'Muchas especies de animales están en peligro de extinción.'),
('es', 'B1', 'środowisko', 'clima', 'klimat', 'El clima de esta región es muy seco en verano.'),
('es', 'B1', 'środowisko', 'basura', 'śmieci', 'Recogimos toda la basura de la playa el domingo.'),
('es', 'B1', 'środowisko', 'renovable', 'odnawialny', 'La energía renovable es más limpia que el carbón.'),
('es', 'B1', 'środowisko', 'combustible', 'paliwo', 'El precio del combustible ha subido mucho este año.'),
('es', 'B1', 'środowisko', 'capa de ozono', 'warstwa ozonowa', 'La capa de ozono nos protege de los rayos del sol.'),
('es', 'B1', 'środowisko', 'deforestación', 'wylesianie', 'La deforestación afecta al clima de todo el planeta.'),
('es', 'B1', 'środowisko', 'desperdicio', 'marnotrawstwo', 'Tirar comida es un desperdicio que debemos evitar.'),
('es', 'B1', 'środowisko', 'naturaleza', 'przyroda', 'Me encanta pasar los fines de semana en plena naturaleza.'),
('es', 'B1', 'środowisko', 'planeta', 'planeta', 'Todos somos responsables de cuidar nuestro planeta.'),
('es', 'B1', 'środowisko', 'atmósfera', 'atmosfera', 'Los gases contaminantes se acumulan en la atmósfera.'),
-- relacje
('es', 'B1', 'relacje', 'amistad', 'przyjaźń', 'Nuestra amistad ha durado más de veinte años.'),
('es', 'B1', 'relacje', 'pareja', 'partner (para)', 'Mi pareja y yo vamos a mudarnos a otra ciudad.'),
('es', 'B1', 'relacje', 'matrimonio', 'małżeństwo', 'Llevan treinta años de matrimonio y siguen felices.'),
('es', 'B1', 'relacje', 'noviazgo', 'związek (przed ślubem)', 'Después de un largo noviazgo, decidieron casarse.'),
('es', 'B1', 'relacje', 'confianza', 'zaufanie', 'La confianza es la base de cualquier relación sana.'),
('es', 'B1', 'relacje', 'cariñoso', 'czuły', 'Es un chico muy cariñoso con su familia.'),
('es', 'B1', 'relacje', 'compromiso', 'zobowiązanie', 'El matrimonio es un compromiso serio para toda la vida.'),
('es', 'B1', 'relacje', 'discusión', 'kłótnia', 'Tuvieron una fuerte discusión por una tontería.'),
('es', 'B1', 'relacje', 'conocido', 'znajomy', 'No es un amigo, solo un conocido del trabajo.'),
('es', 'B1', 'relacje', 'vecino', 'sąsiad', 'Mi vecino siempre me ayuda cuando lo necesito.'),
('es', 'B1', 'relacje', 'suegra', 'teściowa', 'Mi suegra cocina la mejor paella del mundo.'),
('es', 'B1', 'relacje', 'cuñado', 'szwagier', 'Mi cuñado vendrá a comer con nosotros el domingo.'),
('es', 'B1', 'relacje', 'compañero', 'kolega (towarzysz)', 'Mi compañero de piso es muy ordenado y tranquilo.'),
('es', 'B1', 'relacje', 'cita', 'randka (spotkanie)', 'Tengo una cita con ella el viernes por la tarde.'),
('es', 'B1', 'relacje', 'ruptura', 'rozstanie', 'La ruptura fue difícil, pero ahora está mucho mejor.'),
('es', 'B1', 'relacje', 'divorcio', 'rozwód', 'Tras el divorcio, decidieron seguir siendo amigos.'),
('es', 'B1', 'relacje', 'boda', 'ślub', 'La boda se celebrará en un pueblo de la costa.'),
('es', 'B1', 'relacje', 'convivencia', 'wspólne mieszkanie', 'La convivencia con otras personas requiere respeto.'),
('es', 'B1', 'relacje', 'fidelidad', 'wierność', 'La fidelidad es muy importante en su relación.'),
('es', 'B1', 'relacje', 'apoyo', 'wsparcie', 'Siempre cuento con el apoyo de mis amigos.'),
('es', 'B1', 'relacje', 'respeto', 'szacunek', 'El respeto mutuo es fundamental entre compañeros.'),
-- media
('es', 'B1', 'media', 'noticia', 'wiadomość', 'La noticia del accidente apareció en todos los periódicos.'),
('es', 'B1', 'media', 'periódico', 'gazeta', 'Leo el periódico todas las mañanas con un café.'),
('es', 'B1', 'media', 'prensa', 'prasa', 'La prensa informó sobre las decisiones del gobierno.'),
('es', 'B1', 'media', 'cadena', 'stacja (telewizyjna)', 'Esa cadena de televisión emite muchos concursos.'),
('es', 'B1', 'media', 'anuncio', 'reklama (ogłoszenie)', 'Vi un anuncio muy divertido durante el partido.'),
('es', 'B1', 'media', 'publicidad', 'reklama', 'La publicidad en internet es cada vez más frecuente.'),
('es', 'B1', 'media', 'reportaje', 'reportaż', 'El reportaje sobre el cambio climático fue muy interesante.'),
('es', 'B1', 'media', 'entrevista', 'wywiad', 'El actor concedió una entrevista a una revista famosa.'),
('es', 'B1', 'media', 'periodista', 'dziennikarz', 'La periodista viajó al país para cubrir el conflicto.'),
('es', 'B1', 'media', 'titular', 'nagłówek', 'El titular del periódico ocupaba toda la portada.'),
('es', 'B1', 'media', 'emisora', 'stacja radiowa', 'Escucho una emisora de radio mientras conduzco.'),
('es', 'B1', 'media', 'audiencia', 'widownia', 'El programa tiene una audiencia de millones de personas.'),
('es', 'B1', 'media', 'suscripción', 'subskrypcja', 'Pagué una suscripción para ver series sin anuncios.'),
('es', 'B1', 'media', 'redes sociales', 'media społecznościowe', 'Muchos jóvenes pasan horas en las redes sociales.'),
('es', 'B1', 'media', 'locutor', 'prezenter (spiker)', 'El locutor presentó las noticias con voz tranquila.'),
('es', 'B1', 'media', 'crónica', 'kronika', 'Escribió una crónica muy detallada del partido.'),
('es', 'B1', 'media', 'reportero', 'reporter', 'El reportero entrevistó a los vecinos del barrio.'),
('es', 'B1', 'media', 'difusión', 'rozpowszechnianie', 'La difusión de la noticia fue muy rápida en internet.'),
('es', 'B1', 'media', 'medios', 'media', 'Los medios de comunicación tienen mucha influencia.'),
('es', 'B1', 'media', 'censura', 'cenzura', 'En algunos países existe censura sobre la prensa.'),
('es', 'B1', 'media', 'rumor', 'plotka', 'Corre el rumor de que van a cerrar la fábrica.'),
-- kultura
('es', 'B1', 'kultura', 'cuadro', 'obraz', 'En el museo hay un cuadro muy famoso de Goya.'),
('es', 'B1', 'kultura', 'escultura', 'rzeźba', 'La escultura de mármol está en el centro de la plaza.'),
('es', 'B1', 'kultura', 'exposición', 'wystawa', 'Visitamos una exposición de arte moderno el sábado.'),
('es', 'B1', 'kultura', 'obra', 'dzieło', 'Esta obra de teatro trata sobre una familia española.'),
('es', 'B1', 'kultura', 'escenario', 'scena', 'Los actores salieron al escenario entre aplausos.'),
('es', 'B1', 'kultura', 'estreno', 'premiera', 'El estreno de la película será el próximo viernes.'),
('es', 'B1', 'kultura', 'guion', 'scenariusz', 'El guion de la serie está lleno de sorpresas.'),
('es', 'B1', 'kultura', 'director', 'reżyser', 'El director de cine explicó cómo hizo la película.'),
('es', 'B1', 'kultura', 'actor', 'aktor', 'Ese actor es muy conocido por sus papeles cómicos.'),
('es', 'B1', 'kultura', 'público', 'publiczność', 'El público aplaudió durante varios minutos al final.'),
('es', 'B1', 'kultura', 'entrada', 'bilet (wstęp)', 'Compré dos entradas para el concierto de esta noche.'),
('es', 'B1', 'kultura', 'museo', 'muzeum', 'El museo abre todos los días excepto los lunes.'),
('es', 'B1', 'kultura', 'patrimonio', 'dziedzictwo', 'Esta ciudad forma parte del patrimonio de la humanidad.'),
('es', 'B1', 'kultura', 'costumbre', 'zwyczaj', 'Cenar tarde es una costumbre muy española.'),
('es', 'B1', 'kultura', 'tradición', 'tradycja', 'La tradición de las Fallas atrae a muchos turistas.'),
('es', 'B1', 'kultura', 'novela', 'powieść', 'Estoy leyendo una novela histórica muy emocionante.'),
('es', 'B1', 'kultura', 'poesía', 'poezja', 'La poesía de este autor es difícil pero muy bella.'),
('es', 'B1', 'kultura', 'pintor', 'malarz', 'Ese pintor vendió su primer cuadro a los veinte años.'),
('es', 'B1', 'kultura', 'taquilla', 'kasa biletowa', 'Compramos las entradas en la taquilla del cine.'),
('es', 'B1', 'kultura', 'espectáculo', 'widowisko', 'El espectáculo de danza duró casi dos horas.'),
('es', 'B1', 'kultura', 'ensayo', 'próba (np. teatralna)', 'Los músicos tienen un ensayo antes del concierto.'),
-- zwroty codzienne
('es', 'B1', 'zwroty codzienne', 'de repente', 'nagle', 'Estábamos paseando y de repente empezó a llover.'),
('es', 'B1', 'zwroty codzienne', 'por supuesto', 'oczywiście', 'Por supuesto que te ayudaré con la mudanza.'),
('es', 'B1', 'zwroty codzienne', 'de vez en cuando', 'od czasu do czasu', 'De vez en cuando salgo a cenar con mis amigos.'),
('es', 'B1', 'zwroty codzienne', 'a menudo', 'często', 'A menudo voy al gimnasio después del trabajo.'),
('es', 'B1', 'zwroty codzienne', 'enseguida', 'natychmiast', 'Siéntate, que la comida estará lista enseguida.'),
('es', 'B1', 'zwroty codzienne', 'o sea', 'czyli', 'Llegó tarde, o sea, perdió el principio de la película.'),
('es', 'B1', 'zwroty codzienne', 'de hecho', 'właściwie (w rzeczywistości)', 'No me gusta el café; de hecho, nunca lo bebo.'),
('es', 'B1', 'zwroty codzienne', 'por cierto', 'à propos', 'Por cierto, ¿sabes a qué hora empieza la reunión?'),
('es', 'B1', 'zwroty codzienne', 'sin embargo', 'jednak', 'Estudió mucho; sin embargo, no aprobó el examen.'),
('es', 'B1', 'zwroty codzienne', 'a lo mejor', 'być może', 'A lo mejor vamos a la playa este fin de semana.'),
('es', 'B1', 'zwroty codzienne', 'de todos modos', 'tak czy inaczej', 'No tengo mucho tiempo, pero de todos modos te ayudaré.'),
('es', 'B1', 'zwroty codzienne', 'en cuanto', 'jak tylko', 'Te llamaré en cuanto llegue a casa.'),
('es', 'B1', 'zwroty codzienne', 'menos mal', 'całe szczęście', 'Menos mal que trajiste el paraguas, está lloviendo.'),
('es', 'B1', 'zwroty codzienne', 'dar igual', 'być wszystko jedno', 'Me da igual el restaurante, elige tú el sitio.'),
('es', 'B1', 'zwroty codzienne', 'tener ganas', 'mieć ochotę', 'Tengo muchas ganas de empezar las vacaciones.'),
('es', 'B1', 'zwroty codzienne', 'echar de menos', 'tęsknić', 'Echo de menos a mi familia cuando estoy fuera.'),
('es', 'B1', 'zwroty codzienne', 'hacer falta', 'być potrzebnym', 'Hace falta más gente para terminar el proyecto.'),
('es', 'B1', 'zwroty codzienne', 'valer la pena', 'być wartym zachodu', 'El viaje fue caro, pero valió la pena totalmente.'),
('es', 'B1', 'zwroty codzienne', 'en fin', 'krótko mówiąc', 'En fin, no ha salido como esperábamos.'),
('es', 'B1', 'zwroty codzienne', 'por lo visto', 'najwyraźniej', 'Por lo visto, van a subir los precios el mes que viene.'),
('es', 'B1', 'zwroty codzienne', 'ni siquiera', 'nawet nie', 'No me llamó; ni siquiera me envió un mensaje.');
