-- ============================================================================
-- Seed: Spanish (es) CEFR A1 vocabulary for Polish-speaking learners
-- Table: vocabulary_words
-- language = 'es', level = 'A1'
-- word_en holds the SPANISH (target) word; translation_pl is the Polish gloss.
-- Idempotent: clears existing es/A1 rows before inserting.
-- ============================================================================

delete from vocabulary_words where language = 'es' and level = 'A1';

insert into vocabulary_words (language, level, category, word_en, translation_pl, example_sentence) values
-- rodzina (family)
('es','A1','rodzina','familia','rodzina','Mi familia es grande.'),
('es','A1','rodzina','madre','matka','Mi madre se llama Ana.'),
('es','A1','rodzina','padre','ojciec','Mi padre trabaja mucho.'),
('es','A1','rodzina','hijo','syn','Su hijo tiene cinco años.'),
('es','A1','rodzina','hija','córka','Tengo una hija pequeña.'),
('es','A1','rodzina','hermano','brat','Mi hermano juega al fútbol.'),
('es','A1','rodzina','hermana','siostra','Mi hermana estudia español.'),
('es','A1','rodzina','abuelo','dziadek','Mi abuelo vive en el pueblo.'),
('es','A1','rodzina','abuela','babcia','Mi abuela cocina muy bien.'),
('es','A1','rodzina','tío','wujek','Mi tío tiene un coche nuevo.'),
('es','A1','rodzina','tía','ciotka','Mi tía vive en Madrid.'),
('es','A1','rodzina','primo','kuzyn','Mi primo es muy simpático.'),
('es','A1','rodzina','prima','kuzynka','Mi prima tiene diez años.'),
('es','A1','rodzina','marido','mąż','El marido de Ana es alto.'),
('es','A1','rodzina','esposa','żona','Su esposa habla italiano.'),
('es','A1','rodzina','nieto','wnuk','El abuelo juega con su nieto.'),
('es','A1','rodzina','nieta','wnuczka','La abuela quiere a su nieta.'),
('es','A1','rodzina','bebé','niemowlę','El bebé duerme en la cama.'),
-- kolory (colors)
('es','A1','kolory','color','kolor','¿Cuál es tu color favorito?'),
('es','A1','kolory','rojo','czerwony','El coche es rojo.'),
('es','A1','kolory','azul','niebieski','El cielo es azul.'),
('es','A1','kolory','verde','zielony','La hierba es verde.'),
('es','A1','kolory','amarillo','żółty','El sol es amarillo.'),
('es','A1','kolory','blanco','biały','El gato es blanco.'),
('es','A1','kolory','negro','czarny','Mi perro es negro.'),
('es','A1','kolory','gris','szary','El cielo está gris hoy.'),
('es','A1','kolory','rosa','różowy','La flor es rosa.'),
('es','A1','kolory','anaranjado','pomarańczowy','El vestido es anaranjado.'),
('es','A1','kolory','marrón','brązowy','El oso es marrón.'),
('es','A1','kolory','morado','fioletowy','Me gusta el color morado.'),
('es','A1','kolory','dorado','złoty','El anillo es dorado.'),
('es','A1','kolory','plateado','srebrny','El reloj es plateado.'),
('es','A1','kolory','claro','jasny','El azul claro es bonito.'),
('es','A1','kolory','oscuro','ciemny','Prefiero el verde oscuro.'),
-- liczby (numbers)
('es','A1','liczby','cero','zero','Cero es un número.'),
('es','A1','liczby','uno','jeden','Solo quiero uno.'),
('es','A1','liczby','dos','dwa','Tengo dos hermanos.'),
('es','A1','liczby','tres','trzy','Hay tres libros en la mesa.'),
('es','A1','liczby','cuatro','cztery','La mesa tiene cuatro patas.'),
('es','A1','liczby','cinco','pięć','Son las cinco de la tarde.'),
('es','A1','liczby','seis','sześć','Compro seis huevos.'),
('es','A1','liczby','siete','siedem','La semana tiene siete días.'),
('es','A1','liczby','ocho','osiem','Me levanto a las ocho.'),
('es','A1','liczby','nueve','dziewięć','Mi hijo tiene nueve años.'),
('es','A1','liczby','diez','dziesięć','Hay diez alumnos en la clase.'),
('es','A1','liczby','once','jedenaście','Son las once de la mañana.'),
('es','A1','liczby','doce','dwanaście','El año tiene doce meses.'),
('es','A1','liczby','trece','trzynaście','Mi hermana tiene trece años.'),
('es','A1','liczby','catorce','czternaście','Hay catorce sillas.'),
('es','A1','liczby','quince','piętnaście','Son las tres y quince.'),
('es','A1','liczby','veinte','dwadzieścia','Tengo veinte euros.'),
('es','A1','liczby','treinta','trzydzieści','El mes tiene treinta días.'),
('es','A1','liczby','cien','sto','Necesito cien euros.'),
('es','A1','liczby','mil','tysiąc','El libro cuesta mil pesos.'),
-- jedzenie (food)
('es','A1','jedzenie','comida','jedzenie','La comida está muy rica.'),
('es','A1','jedzenie','pan','chleb','Como pan por la mañana.'),
('es','A1','jedzenie','agua','woda','Bebo agua todos los días.'),
('es','A1','jedzenie','leche','mleko','El niño bebe leche.'),
('es','A1','jedzenie','queso','ser (żółty)','Me gusta el queso.'),
('es','A1','jedzenie','huevo','jajko','Como un huevo para desayunar.'),
('es','A1','jedzenie','carne','mięso','No como carne.'),
('es','A1','jedzenie','pescado','ryba (danie)','El pescado está fresco.'),
('es','A1','jedzenie','pollo','kurczak','Hoy comemos pollo con arroz.'),
('es','A1','jedzenie','fruta','owoc','La fruta es sana.'),
('es','A1','jedzenie','manzana','jabłko','Como una manzana roja.'),
('es','A1','jedzenie','naranja','pomarańcza','La naranja tiene mucha vitamina.'),
('es','A1','jedzenie','plátano','banan','El mono come un plátano.'),
('es','A1','jedzenie','tomate','pomidor','La ensalada tiene tomate.'),
('es','A1','jedzenie','patata','ziemniak','Me gustan las patatas fritas.'),
('es','A1','jedzenie','arroz','ryż','El arroz está caliente.'),
('es','A1','jedzenie','café','kawa','Bebo café por la mañana.'),
('es','A1','jedzenie','té','herbata','¿Quieres un té?'),
('es','A1','jedzenie','azúcar','cukier','El café tiene mucho azúcar.'),
('es','A1','jedzenie','sal','sól','La sopa necesita sal.'),
-- dom (home)
('es','A1','dom','casa','dom','Mi casa es pequeña.'),
('es','A1','dom','puerta','drzwi','La puerta está abierta.'),
('es','A1','dom','ventana','okno','Abro la ventana por la mañana.'),
('es','A1','dom','mesa','stół','Los libros están sobre la mesa.'),
('es','A1','dom','silla','krzesło','La silla es cómoda.'),
('es','A1','dom','cama','łóżko','Duermo en mi cama.'),
('es','A1','dom','cocina','kuchnia','Mi madre está en la cocina.'),
('es','A1','dom','baño','łazienka','El baño está a la derecha.'),
('es','A1','dom','habitación','pokój','Mi habitación es grande.'),
('es','A1','dom','salón','salon','Vemos la tele en el salón.'),
('es','A1','dom','sofá','kanapa','El gato duerme en el sofá.'),
('es','A1','dom','lámpara','lampa','La lámpara está encendida.'),
('es','A1','dom','llave','klucz','No encuentro la llave.'),
('es','A1','dom','suelo','podłoga','El suelo está limpio.'),
('es','A1','dom','pared','ściana','Hay un cuadro en la pared.'),
('es','A1','dom','jardín','ogród','Jugamos en el jardín.'),
('es','A1','dom','espejo','lustro','Me miro en el espejo.'),
('es','A1','dom','armario','szafa','La ropa está en el armario.'),
-- dni tygodnia (days of the week)
('es','A1','dni tygodnia','lunes','poniedziałek','El lunes empiezo a trabajar.'),
('es','A1','dni tygodnia','martes','wtorek','El martes tengo clase de español.'),
('es','A1','dni tygodnia','miércoles','środa','El miércoles voy al médico.'),
('es','A1','dni tygodnia','jueves','czwartek','El jueves como con mi familia.'),
('es','A1','dni tygodnia','viernes','piątek','El viernes salgo con amigos.'),
('es','A1','dni tygodnia','sábado','sobota','El sábado no trabajo.'),
('es','A1','dni tygodnia','domingo','niedziela','El domingo descanso en casa.'),
('es','A1','dni tygodnia','semana','tydzień','La semana tiene siete días.'),
('es','A1','dni tygodnia','fin de semana','weekend','Este fin de semana voy a la playa.'),
('es','A1','dni tygodnia','hoy','dziś','Hoy hace buen tiempo.'),
('es','A1','dni tygodnia','ayer','wczoraj','Ayer comí pescado.'),
('es','A1','dni tygodnia','mañana','jutro (też: rano)','Mañana voy al trabajo.'),
-- czas/godziny (time/hours)
('es','A1','czas/godziny','tiempo','czas','No tengo tiempo hoy.'),
('es','A1','czas/godziny','hora','godzina','¿Qué hora es?'),
('es','A1','czas/godziny','minuto','minuta','Espera un minuto, por favor.'),
('es','A1','czas/godziny','segundo','sekunda','Solo dura un segundo.'),
('es','A1','czas/godziny','día','dzień','Hoy es un buen día.'),
('es','A1','czas/godziny','noche','noc','Por la noche leo un libro.'),
('es','A1','czas/godziny','tarde','popołudnie','Por la tarde estudio español.'),
('es','A1','czas/godziny','mediodía','południe','Comemos al mediodía.'),
('es','A1','czas/godziny','medianoche','północ','La fiesta termina a medianoche.'),
('es','A1','czas/godziny','reloj','zegar','El reloj está en la pared.'),
('es','A1','czas/godziny','año','rok','El año tiene doce meses.'),
('es','A1','czas/godziny','mes','miesiąc','Este mes hace calor.'),
('es','A1','czas/godziny','temprano','wcześnie','Me levanto muy temprano.'),
('es','A1','czas/godziny','ahora','teraz','Ahora estoy en casa.'),
('es','A1','czas/godziny','cuarto','kwadrans','Son las dos y cuarto.'),
('es','A1','czas/godziny','media','pół (godziny)','Son las tres y media.'),
-- podstawowe czasowniki (basic verbs)
('es','A1','podstawowe czasowniki','ser','być','Yo soy de Polonia.'),
('es','A1','podstawowe czasowniki','estar','być (znajdować się)','Estoy en casa ahora.'),
('es','A1','podstawowe czasowniki','tener','mieć','Tengo dos gatos.'),
('es','A1','podstawowe czasowniki','hacer','robić','¿Qué haces hoy?'),
('es','A1','podstawowe czasowniki','ir','iść / jechać','Voy al colegio en autobús.'),
('es','A1','podstawowe czasowniki','comer','jeść','Como fruta cada día.'),
('es','A1','podstawowe czasowniki','beber','pić','Bebo mucha agua.'),
('es','A1','podstawowe czasowniki','hablar','mówić','Hablo un poco de español.'),
('es','A1','podstawowe czasowniki','vivir','mieszkać / żyć','Vivo en una casa grande.'),
('es','A1','podstawowe czasowniki','querer','chcieć','Quiero un café, por favor.'),
('es','A1','podstawowe czasowniki','poder','móc','¿Puedes ayudarme?'),
('es','A1','podstawowe czasowniki','ver','widzieć','No veo bien sin gafas.'),
('es','A1','podstawowe czasowniki','dar','dawać','Te doy un regalo.'),
('es','A1','podstawowe czasowniki','saber','wiedzieć','No sé la respuesta.'),
('es','A1','podstawowe czasowniki','venir','przychodzić','¿Vienes a mi casa?'),
('es','A1','podstawowe czasowniki','decir','powiedzieć','Ella dice la verdad.'),
('es','A1','podstawowe czasowniki','leer','czytać','Leo el periódico por la mañana.'),
('es','A1','podstawowe czasowniki','escribir','pisać','Escribo una carta a mi amigo.'),
('es','A1','podstawowe czasowniki','dormir','spać','Duermo ocho horas.'),
('es','A1','podstawowe czasowniki','comprar','kupować','Compro pan en la tienda.'),
-- ubrania (clothes)
('es','A1','ubrania','ropa','ubrania','La ropa está limpia.'),
('es','A1','ubrania','camisa','koszula','Llevo una camisa blanca.'),
('es','A1','ubrania','camiseta','koszulka','Me pongo una camiseta azul.'),
('es','A1','ubrania','pantalón','spodnie','El pantalón es negro.'),
('es','A1','ubrania','falda','spódnica','Ella lleva una falda roja.'),
('es','A1','ubrania','vestido','sukienka','El vestido es muy bonito.'),
('es','A1','ubrania','zapato','but','Mi zapato es marrón.'),
('es','A1','ubrania','calcetín','skarpetka','Necesito un calcetín limpio.'),
('es','A1','ubrania','abrigo','płaszcz','En invierno llevo abrigo.'),
('es','A1','ubrania','chaqueta','kurtka','Hace frío, ponte la chaqueta.'),
('es','A1','ubrania','jersey','sweter','El jersey es de lana.'),
('es','A1','ubrania','sombrero','kapelusz','El hombre lleva un sombrero.'),
('es','A1','ubrania','gorra','czapka (z daszkiem)','El niño lleva una gorra.'),
('es','A1','ubrania','bufanda','szalik','La bufanda es muy caliente.'),
('es','A1','ubrania','guante','rękawiczka','Pierdo un guante cada invierno.'),
('es','A1','ubrania','cinturón','pasek','El cinturón es de cuero.'),
('es','A1','ubrania','corbata','krawat','Mi padre lleva corbata al trabajo.'),
-- zwierzęta (animals)
('es','A1','zwierzęta','animal','zwierzę','El perro es mi animal favorito.'),
('es','A1','zwierzęta','perro','pies','Mi perro corre en el parque.'),
('es','A1','zwierzęta','gato','kot','El gato duerme todo el día.'),
('es','A1','zwierzęta','caballo','koń','El caballo es muy rápido.'),
('es','A1','zwierzęta','vaca','krowa','La vaca come hierba.'),
('es','A1','zwierzęta','cerdo','świnia','El cerdo vive en la granja.'),
('es','A1','zwierzęta','oveja','owca','La oveja tiene lana blanca.'),
('es','A1','zwierzęta','gallina','kura','La gallina pone huevos.'),
('es','A1','zwierzęta','pájaro','ptak','El pájaro canta por la mañana.'),
('es','A1','zwierzęta','pez','ryba (żywa)','El pez nada en el agua.'),
('es','A1','zwierzęta','ratón','mysz','El gato caza un ratón.'),
('es','A1','zwierzęta','conejo','królik','El conejo come zanahorias.'),
('es','A1','zwierzęta','león','lew','El león vive en África.'),
('es','A1','zwierzęta','elefante','słoń','El elefante es muy grande.'),
('es','A1','zwierzęta','mono','małpa','El mono come plátanos.'),
('es','A1','zwierzęta','oso','niedźwiedź','El oso duerme en invierno.'),
('es','A1','zwierzęta','pato','kaczka','El pato nada en el lago.'),
('es','A1','zwierzęta','tortuga','żółw','La tortuga camina despacio.');
