-- Seed: Spanish (es) CEFR B2 vocabulary for Polish speakers
-- Table: vocabulary_words  (language='es', level='B2')
-- word_en holds the SPANISH word (target language); translation_pl is the Polish gloss;
-- example_sentence is a natural B2-level sentence in Spanish.
-- Idempotent: clears existing es/B2 rows before inserting.

delete from vocabulary_words where language = 'es' and level = 'B2';

insert into vocabulary_words (language, level, category, word_en, translation_pl, example_sentence) values
-- biznes
('es', 'B2', 'biznes', 'empresa', 'firma / przedsiębiorstwo', 'La empresa ha decidido expandirse a mercados internacionales el próximo año.'),
('es', 'B2', 'biznes', 'facturación', 'obroty / fakturowanie', 'La facturación de la compañía aumentó un quince por ciento respecto al ejercicio anterior.'),
('es', 'B2', 'biznes', 'proveedor', 'dostawca', 'Tuvimos que cambiar de proveedor porque los plazos de entrega eran demasiado largos.'),
('es', 'B2', 'biznes', 'accionista', 'akcjonariusz', 'Los accionistas se reunieron para votar el reparto de dividendos.'),
('es', 'B2', 'biznes', 'rentabilidad', 'rentowność', 'La rentabilidad del negocio depende en gran medida de reducir los costes fijos.'),
('es', 'B2', 'biznes', 'plantilla', 'kadra / personel', 'La empresa amplió su plantilla tras firmar el nuevo contrato.'),
('es', 'B2', 'biznes', 'fusión', 'fuzja', 'La fusión entre las dos entidades bancarias creó el mayor grupo del país.'),
('es', 'B2', 'biznes', 'gerente', 'kierownik / menedżer', 'El gerente convocó una reunión urgente para analizar las pérdidas.'),
('es', 'B2', 'biznes', 'presupuesto', 'budżet', 'El departamento de marketing agotó su presupuesto antes de fin de año.'),
('es', 'B2', 'biznes', 'inversión', 'inwestycja', 'La inversión en tecnología resultó clave para mejorar la productividad.'),
('es', 'B2', 'biznes', 'sucursal', 'filia / oddział', 'El banco cerró varias sucursales para reducir gastos operativos.'),
('es', 'B2', 'biznes', 'competidor', 'konkurent', 'Nuestro principal competidor acaba de lanzar un producto muy similar.'),
('es', 'B2', 'biznes', 'negociación', 'negocjacja', 'La negociación del convenio colectivo se prolongó durante meses.'),
('es', 'B2', 'biznes', 'despido', 'zwolnienie z pracy', 'El despido improcedente le costó a la empresa una fuerte indemnización.'),
('es', 'B2', 'biznes', 'contratación', 'zatrudnianie / rekrutacja', 'El proceso de contratación incluye varias entrevistas y una prueba técnica.'),
('es', 'B2', 'biznes', 'beneficio', 'zysk', 'La empresa reinvirtió gran parte de sus beneficios en investigación.'),
('es', 'B2', 'biznes', 'filial', 'spółka zależna', 'La multinacional abrió una filial en México para operar en la región.'),
('es', 'B2', 'biznes', 'emprendedor', 'przedsiębiorca', 'Muchos jóvenes emprendedores buscan financiación para sus proyectos.'),
('es', 'B2', 'biznes', 'cartera de clientes', 'portfel klientów', 'El comercial se marchó de la empresa llevándose gran parte de la cartera de clientes.'),
('es', 'B2', 'biznes', 'junta directiva', 'zarząd', 'La junta directiva aprobó por unanimidad el plan estratégico.'),
('es', 'B2', 'biznes', 'balance', 'bilans', 'El balance anual refleja una situación financiera saneada.'),
-- polityka
('es', 'B2', 'polityka', 'gobierno', 'rząd', 'El gobierno anunció una serie de reformas para reactivar la economía.'),
('es', 'B2', 'polityka', 'diputado', 'poseł', 'El diputado presentó una enmienda a la ley durante el debate.'),
('es', 'B2', 'polityka', 'oposición', 'opozycja', 'La oposición criticó duramente los presupuestos presentados por el ejecutivo.'),
('es', 'B2', 'polityka', 'elecciones', 'wybory', 'Las elecciones se celebrarán el último domingo del mes que viene.'),
('es', 'B2', 'polityka', 'escaño', 'mandat poselski', 'El partido perdió varios escaños en el parlamento tras los comicios.'),
('es', 'B2', 'polityka', 'mandato', 'kadencja', 'Durante su mandato, la alcaldesa impulsó numerosas obras públicas.'),
('es', 'B2', 'polityka', 'coalición', 'koalicja', 'Los dos partidos formaron una coalición para poder gobernar.'),
('es', 'B2', 'polityka', 'cumbre', 'szczyt (spotkanie)', 'Los líderes europeos se reunieron en una cumbre para abordar la crisis migratoria.'),
('es', 'B2', 'polityka', 'soberanía', 'suwerenność', 'El conflicto puso en cuestión la soberanía del país sobre esos territorios.'),
('es', 'B2', 'polityka', 'referéndum', 'referendum', 'El gobierno convocó un referéndum para decidir sobre la reforma constitucional.'),
('es', 'B2', 'polityka', 'partido', 'partia', 'El partido celebró su congreso para elegir a un nuevo líder.'),
('es', 'B2', 'polityka', 'ciudadanía', 'obywatelstwo / obywatele', 'La ciudadanía exigió mayor transparencia a sus representantes.'),
('es', 'B2', 'polityka', 'corrupción', 'korupcja', 'El escándalo de corrupción obligó a dimitir a varios ministros.'),
('es', 'B2', 'polityka', 'dictadura', 'dyktatura', 'Tras décadas de dictadura, el país inició una transición hacia la democracia.'),
('es', 'B2', 'polityka', 'sufragio', 'prawo wyborcze / głosowanie', 'El sufragio universal permitió que todos los adultos pudieran votar.'),
('es', 'B2', 'polityka', 'campaña', 'kampania', 'Durante la campaña electoral, los candidatos recorrieron todo el país.'),
('es', 'B2', 'polityka', 'portavoz', 'rzecznik', 'El portavoz del gobierno desmintió los rumores en rueda de prensa.'),
('es', 'B2', 'polityka', 'veto', 'weto', 'El presidente ejerció su derecho de veto sobre la nueva ley.'),
('es', 'B2', 'polityka', 'tratado', 'traktat', 'Ambos países firmaron un tratado de libre comercio.'),
('es', 'B2', 'polityka', 'legislatura', 'kadencja parlamentu', 'La reforma quedó pendiente para la próxima legislatura.'),
('es', 'B2', 'polityka', 'abstención', 'wstrzymanie się od głosu', 'La alta abstención marcó los resultados de las últimas elecciones.'),
-- nauka
('es', 'B2', 'nauka', 'investigación', 'badanie (naukowe)', 'La investigación sobre el cáncer ha logrado avances muy prometedores.'),
('es', 'B2', 'nauka', 'hipótesis', 'hipoteza', 'Los datos recogidos no confirman la hipótesis inicial de los científicos.'),
('es', 'B2', 'nauka', 'experimento', 'eksperyment', 'El experimento se repitió varias veces para garantizar resultados fiables.'),
('es', 'B2', 'nauka', 'célula', 'komórka', 'Cada célula del cuerpo contiene toda la información genética del individuo.'),
('es', 'B2', 'nauka', 'molécula', 'cząsteczka', 'Una molécula de agua está formada por dos átomos de hidrógeno y uno de oxígeno.'),
('es', 'B2', 'nauka', 'gravedad', 'grawitacja', 'La gravedad hace que los objetos caigan hacia el centro de la Tierra.'),
('es', 'B2', 'nauka', 'genética', 'genetyka', 'Los avances en genética permiten prevenir ciertas enfermedades hereditarias.'),
('es', 'B2', 'nauka', 'vacuna', 'szczepionka', 'El desarrollo de la vacuna requirió años de ensayos rigurosos.'),
('es', 'B2', 'nauka', 'átomo', 'atom', 'El átomo es la unidad más pequeña que conserva las propiedades de un elemento.'),
('es', 'B2', 'nauka', 'teoría', 'teoria', 'La teoría de la evolución explica la diversidad de las especies.'),
('es', 'B2', 'nauka', 'descubrimiento', 'odkrycie', 'El descubrimiento de la penicilina revolucionó la medicina moderna.'),
('es', 'B2', 'nauka', 'laboratorio', 'laboratorium', 'Los investigadores pasaron meses en el laboratorio analizando las muestras.'),
('es', 'B2', 'nauka', 'especie', 'gatunek', 'Muchas especies están en peligro de extinción por la actividad humana.'),
('es', 'B2', 'nauka', 'evolución', 'ewolucja', 'La evolución de las especies se produce a lo largo de millones de años.'),
('es', 'B2', 'nauka', 'partícula', 'cząstka', 'Los físicos estudian el comportamiento de las partículas subatómicas.'),
('es', 'B2', 'nauka', 'neurona', 'neuron', 'Cada neurona se conecta con miles de células vecinas del cerebro.'),
('es', 'B2', 'nauka', 'ensayo clínico', 'badanie kliniczne', 'El nuevo fármaco superó con éxito la fase final del ensayo clínico.'),
('es', 'B2', 'nauka', 'muestra', 'próbka', 'Los científicos analizaron una muestra de sangre para detectar el virus.'),
('es', 'B2', 'nauka', 'cerebro', 'mózg', 'El cerebro humano consume una cantidad enorme de energía.'),
('es', 'B2', 'nauka', 'galaxia', 'galaktyka', 'Nuestra galaxia contiene miles de millones de estrellas.'),
('es', 'B2', 'nauka', 'microbio', 'drobnoustrój', 'Algunos microbios resultan beneficiosos para la digestión.'),
-- media
('es', 'B2', 'media', 'periodista', 'dziennikarz', 'El periodista destapó un caso de corrupción tras meses de investigación.'),
('es', 'B2', 'media', 'titular', 'nagłówek', 'El titular de la portada exageraba claramente los hechos.'),
('es', 'B2', 'media', 'reportaje', 'reportaż', 'El reportaje sobre el cambio climático ganó un premio internacional.'),
('es', 'B2', 'media', 'audiencia', 'widownia / oglądalność', 'El programa batió récords de audiencia en su estreno.'),
('es', 'B2', 'media', 'cadena', 'stacja (telewizyjna)', 'La cadena de televisión emitió el debate en horario de máxima audiencia.'),
('es', 'B2', 'media', 'emisora', 'rozgłośnia', 'La emisora de radio entrevistó al ministro esta mañana.'),
('es', 'B2', 'media', 'difundir', 'rozpowszechniać', 'Las redes sociales permiten difundir noticias en cuestión de segundos.'),
('es', 'B2', 'media', 'censura', 'cenzura', 'La censura impidió que muchos periódicos publicaran la verdad.'),
('es', 'B2', 'media', 'rueda de prensa', 'konferencja prasowa', 'El entrenador ofreció una rueda de prensa tras la derrota.'),
('es', 'B2', 'media', 'primicia', 'newsy / wyłączność (scoop)', 'El diario publicó la primicia antes que ningún otro medio.'),
('es', 'B2', 'media', 'cobertura', 'relacja / zasięg', 'La cobertura informativa del suceso fue exhaustiva.'),
('es', 'B2', 'media', 'redacción', 'redakcja', 'La redacción del periódico trabajó toda la noche para cerrar la edición.'),
('es', 'B2', 'media', 'suscriptor', 'subskrybent / prenumerator', 'El periódico digital superó el millón de suscriptores.'),
('es', 'B2', 'media', 'publicidad', 'reklama', 'La publicidad engañosa está prohibida por la ley.'),
('es', 'B2', 'media', 'desinformación', 'dezinformacja', 'La desinformación se propaga con facilidad en tiempos de crisis.'),
('es', 'B2', 'media', 'corresponsal', 'korespondent', 'El corresponsal informó en directo desde la zona del conflicto.'),
('es', 'B2', 'media', 'entrevista', 'wywiad', 'En la entrevista, el escritor habló de su última novela.'),
('es', 'B2', 'media', 'crónica', 'kronika / relacja', 'El periodista escribió una crónica detallada del partido.'),
('es', 'B2', 'media', 'tertulia', 'debata / dyskusja', 'La tertulia radiofónica reunió a varios expertos en economía.'),
('es', 'B2', 'media', 'locutor', 'lektor / spiker', 'El locutor leyó las noticias con una voz muy pausada.'),
('es', 'B2', 'media', 'portada', 'okładka / strona tytułowa', 'La noticia ocupó la portada de todos los diarios nacionales.'),
-- idiomy
('es', 'B2', 'idiomy', 'estar en las nubes', 'bujać w obłokach', 'No te has enterado de nada porque siempre estás en las nubes.'),
('es', 'B2', 'idiomy', 'costar un ojo de la cara', 'kosztować majątek', 'Ese coche deportivo cuesta un ojo de la cara.'),
('es', 'B2', 'idiomy', 'tomar el pelo', 'nabijać się / robić kogoś w konia', 'No me tomes el pelo, sé perfectamente lo que ocurrió.'),
('es', 'B2', 'idiomy', 'echar una mano', 'pomóc / podać pomocną dłoń', 'Si necesitas ayuda con la mudanza, puedo echarte una mano.'),
('es', 'B2', 'idiomy', 'meter la pata', 'popełnić gafę', 'Metí la pata al mencionar la fiesta sorpresa delante de ella.'),
('es', 'B2', 'idiomy', 'no tener pelos en la lengua', 'mówić prosto z mostu', 'Mi jefe no tiene pelos en la lengua y siempre dice lo que piensa.'),
('es', 'B2', 'idiomy', 'ser pan comido', 'być bułką z masłem', 'El examen fue pan comido después de tanto estudiar.'),
('es', 'B2', 'idiomy', 'tirar la toalla', 'rzucić ręcznik / poddać się', 'A pesar de las dificultades, no pienso tirar la toalla.'),
('es', 'B2', 'idiomy', 'dar en el clavo', 'trafić w sedno', 'Con esa propuesta diste en el clavo y todos quedaron satisfechos.'),
('es', 'B2', 'idiomy', 'ponerse las pilas', 'wziąć się do roboty', 'Tienes que ponerte las pilas si quieres aprobar el curso.'),
('es', 'B2', 'idiomy', 'estar hecho polvo', 'być wykończonym', 'Después del maratón, estaba hecho polvo.'),
('es', 'B2', 'idiomy', 'buscarle tres pies al gato', 'szukać dziury w całym', 'Deja de buscarle tres pies al gato y acepta la explicación.'),
('es', 'B2', 'idiomy', 'quedarse de piedra', 'zaniemówić / osłupieć', 'Me quedé de piedra cuando me dieron la noticia.'),
('es', 'B2', 'idiomy', 'hablar por los codos', 'gadać jak najęty', 'Mi vecina habla por los codos y nunca deja hablar a nadie.'),
('es', 'B2', 'idiomy', 'ir al grano', 'przejść do sedna', 'No te andes por las ramas y ve al grano.'),
('es', 'B2', 'idiomy', 'estar como una cabra', 'być stukniętym', 'Tu primo está como una cabra, pero es muy divertido.'),
('es', 'B2', 'idiomy', 'matar dos pájaros de un tiro', 'upiec dwie pieczenie na jednym ogniu', 'Yendo al centro mato dos pájaros de un tiro: hago la compra y visito a mi tía.'),
('es', 'B2', 'idiomy', 'lavarse las manos', 'umywać ręce', 'El director se lavó las manos y culpó a sus empleados del error.'),
('es', 'B2', 'idiomy', 'tener la sartén por el mango', 'trzymać wszystko w garści', 'En esta negociación, nosotros tenemos la sartén por el mango.'),
('es', 'B2', 'idiomy', 'dar gato por liebre', 'oszukać / wcisnąć kit', 'Ten cuidado con esa tienda, suelen dar gato por liebre.'),
('es', 'B2', 'idiomy', 'a duras penas', 'z trudem / ledwo', 'A duras penas conseguimos llegar a tiempo a la reunión.'),
-- prawo
('es', 'B2', 'prawo', 'querella', 'skarga / pozew (karny)', 'La empresa presentó una querella contra el antiguo directivo por fraude.'),
('es', 'B2', 'prawo', 'juez', 'sędzia', 'El juez desestimó las pruebas presentadas por la defensa.'),
('es', 'B2', 'prawo', 'abogado', 'adwokat', 'Su abogado le aconsejó no declarar ante la policía.'),
('es', 'B2', 'prawo', 'sentencia', 'wyrok', 'La sentencia condenó al acusado a cinco años de prisión.'),
('es', 'B2', 'prawo', 'testigo', 'świadek', 'El testigo aseguró no haber visto al sospechoso esa noche.'),
('es', 'B2', 'prawo', 'delito', 'przestępstwo', 'El fraude fiscal es considerado un delito grave.'),
('es', 'B2', 'prawo', 'juicio', 'proces (sądowy)', 'El juicio se aplazó por la ausencia de un testigo clave.'),
('es', 'B2', 'prawo', 'fiscal', 'prokurator', 'El fiscal solicitó una pena de diez años para el acusado.'),
('es', 'B2', 'prawo', 'culpable', 'winny', 'El jurado lo declaró culpable de todos los cargos.'),
('es', 'B2', 'prawo', 'cárcel', 'więzienie', 'Pasó tres años en la cárcel antes de que revisaran su caso.'),
('es', 'B2', 'prawo', 'recurso', 'odwołanie / apelacja', 'La defensa presentó un recurso contra la sentencia.'),
('es', 'B2', 'prawo', 'legislación', 'ustawodawstwo', 'La nueva legislación endurece las penas por delitos ambientales.'),
('es', 'B2', 'prawo', 'contrato', 'umowa', 'Antes de firmar el contrato, conviene leer bien la letra pequeña.'),
('es', 'B2', 'prawo', 'herencia', 'spadek', 'Los hermanos discutieron durante años por el reparto de la herencia.'),
('es', 'B2', 'prawo', 'tribunal', 'sąd / trybunał', 'El tribunal supremo confirmó la resolución de la instancia anterior.'),
('es', 'B2', 'prawo', 'condena', 'skazanie / wyrok skazujący', 'La condena fue reducida por buen comportamiento.'),
('es', 'B2', 'prawo', 'multa', 'grzywna / mandat', 'Le impusieron una multa considerable por exceso de velocidad.'),
('es', 'B2', 'prawo', 'acusado', 'oskarżony', 'El acusado se declaró inocente ante el tribunal.'),
('es', 'B2', 'prawo', 'testimonio', 'zeznanie', 'El testimonio de la víctima resultó decisivo para el veredicto.'),
('es', 'B2', 'prawo', 'jurado', 'ława przysięgłych', 'El jurado deliberó durante horas antes de emitir su veredicto.'),
('es', 'B2', 'prawo', 'indemnización', 'odszkodowanie', 'La aseguradora tardó meses en pagar la indemnización.'),
-- ekonomia
('es', 'B2', 'ekonomia', 'inflación', 'inflacja', 'La inflación ha reducido notablemente el poder adquisitivo de las familias.'),
('es', 'B2', 'ekonomia', 'desempleo', 'bezrobocie', 'La tasa de desempleo juvenil sigue siendo alarmante en la región.'),
('es', 'B2', 'ekonomia', 'deuda', 'dług', 'El país necesita renegociar su deuda con los organismos internacionales.'),
('es', 'B2', 'ekonomia', 'impuesto', 'podatek', 'El gobierno anunció una subida del impuesto sobre el tabaco.'),
('es', 'B2', 'ekonomia', 'mercado', 'rynek', 'El mercado reaccionó con nerviosismo ante las declaraciones del banco central.'),
('es', 'B2', 'ekonomia', 'oferta', 'podaż', 'Cuando la oferta supera a la demanda, los precios tienden a bajar.'),
('es', 'B2', 'ekonomia', 'demanda', 'popyt', 'La demanda de vivienda se ha disparado en las grandes ciudades.'),
('es', 'B2', 'ekonomia', 'recesión', 'recesja', 'Los expertos advierten de que la economía podría entrar en recesión.'),
('es', 'B2', 'ekonomia', 'divisa', 'waluta (obca)', 'La divisa nacional se depreció frente al dólar.'),
('es', 'B2', 'ekonomia', 'bolsa', 'giełda', 'La bolsa cerró la jornada con fuertes pérdidas.'),
('es', 'B2', 'ekonomia', 'crecimiento', 'wzrost (gospodarczy)', 'El crecimiento económico se ralentizó durante el último trimestre.'),
('es', 'B2', 'ekonomia', 'crisis', 'kryzys', 'La crisis financiera afectó a millones de trabajadores.'),
('es', 'B2', 'ekonomia', 'tipo de interés', 'stopa procentowa', 'El banco central decidió subir el tipo de interés para frenar la inflación.'),
('es', 'B2', 'ekonomia', 'patrimonio', 'majątek', 'Invirtió parte de su patrimonio en bienes inmuebles.'),
('es', 'B2', 'ekonomia', 'subvención', 'dotacja', 'Los agricultores recibieron una subvención para modernizar sus explotaciones.'),
('es', 'B2', 'ekonomia', 'aranceles', 'cła', 'Los nuevos aranceles encarecieron los productos importados.'),
('es', 'B2', 'ekonomia', 'quiebra', 'bankructwo', 'La empresa se declaró en quiebra tras años de pérdidas.'),
('es', 'B2', 'ekonomia', 'ahorro', 'oszczędności', 'La subida de precios ha mermado el ahorro de los hogares.'),
('es', 'B2', 'ekonomia', 'salario', 'pensja / wynagrodzenie', 'El salario mínimo se revisa cada año en función de la inflación.'),
('es', 'B2', 'ekonomia', 'producto interior bruto', 'produkt krajowy brutto', 'El producto interior bruto creció un dos por ciento el año pasado.'),
('es', 'B2', 'ekonomia', 'balanza comercial', 'bilans handlowy', 'El país registró un déficit en su balanza comercial.'),
-- zwroty zaawansowane
('es', 'B2', 'zwroty zaawansowane', 'por consiguiente', 'w związku z tym / zatem', 'No presentó la documentación a tiempo y, por consiguiente, quedó descalificado.'),
('es', 'B2', 'zwroty zaawansowane', 'no obstante', 'niemniej jednak', 'El plan es ambicioso; no obstante, resulta difícil de financiar.'),
('es', 'B2', 'zwroty zaawansowane', 'de hecho', 'w rzeczywistości / właściwie', 'No me molesta en absoluto; de hecho, me parece una buena idea.'),
('es', 'B2', 'zwroty zaawansowane', 'a pesar de', 'pomimo', 'A pesar de las críticas, el proyecto siguió adelante.'),
('es', 'B2', 'zwroty zaawansowane', 'en cuanto a', 'jeśli chodzi o', 'En cuanto a los plazos, todavía no hay nada decidido.'),
('es', 'B2', 'zwroty zaawansowane', 'sin embargo', 'jednak', 'Estudió mucho; sin embargo, no logró aprobar el examen.'),
('es', 'B2', 'zwroty zaawansowane', 'por lo tanto', 'dlatego', 'Las pruebas son concluyentes y, por lo tanto, no cabe duda alguna.'),
('es', 'B2', 'zwroty zaawansowane', 'a fin de cuentas', 'koniec końców', 'A fin de cuentas, lo importante es que todos salieron ilesos.'),
('es', 'B2', 'zwroty zaawansowane', 'dar por sentado', 'uznawać za oczywiste', 'No des por sentado que te van a ayudar sin pedirlo.'),
('es', 'B2', 'zwroty zaawansowane', 'hacer hincapié', 'kłaść nacisk / podkreślać', 'El profesor hizo hincapié en la importancia de la puntualidad.'),
('es', 'B2', 'zwroty zaawansowane', 'tener en cuenta', 'brać pod uwagę', 'Hay que tener en cuenta todos los factores antes de decidir.'),
('es', 'B2', 'zwroty zaawansowane', 'llevar a cabo', 'przeprowadzić / zrealizować', 'El equipo llevó a cabo el proyecto en un tiempo récord.'),
('es', 'B2', 'zwroty zaawansowane', 'poner de manifiesto', 'uwidocznić / ujawnić', 'El informe puso de manifiesto graves deficiencias en el sistema.'),
('es', 'B2', 'zwroty zaawansowane', 'a raíz de', 'w wyniku / na skutek', 'A raíz del escándalo, el ministro se vio obligado a dimitir.'),
('es', 'B2', 'zwroty zaawansowane', 'de ahí que', 'stąd / dlatego', 'No estudió nada, de ahí que suspendiera el examen.'),
('es', 'B2', 'zwroty zaawansowane', 'en aras de', 'w imię / dla dobra', 'Renunciaron a parte del beneficio en aras de un acuerdo duradero.'),
('es', 'B2', 'zwroty zaawansowane', 'a menudo', 'często', 'A menudo confundimos la amabilidad con la debilidad.'),
('es', 'B2', 'zwroty zaawansowane', 'por ende', 'a zatem / w konsekwencji', 'El contrato es nulo y, por ende, carece de validez.'),
('es', 'B2', 'zwroty zaawansowane', 'cabe destacar', 'warto podkreślić', 'Cabe destacar el enorme esfuerzo realizado por todo el equipo.'),
('es', 'B2', 'zwroty zaawansowane', 'dando por hecho', 'zakładając (że)', 'Actuó dando por hecho que contaba con nuestro apoyo.'),
('es', 'B2', 'zwroty zaawansowane', 'a grandes rasgos', 'w ogólnym zarysie', 'A grandes rasgos, el plan consiste en reducir gastos y aumentar ingresos.');
