-- ============================================================================
-- Seed: Spanish (es) CEFR A2 vocabulary for Polish-speaking learners
-- Table: vocabulary_words
-- language = 'es', level = 'A2'
-- word_en holds the SPANISH word; translation_pl holds the Polish translation.
-- Categories (Polish labels): podróże, praca, zakupy, pogoda,
--                             zdrowie, czas wolny, transport, uczucia podstawowe
-- Idempotent: deletes existing es/A2 rows before inserting.
-- ============================================================================

delete from vocabulary_words where language = 'es' and level = 'A2';

insert into vocabulary_words (language, level, category, word_en, translation_pl, example_sentence) values
-- ---------- podróże ----------
('es', 'A2', 'podróże', 'el viaje', 'podróż', 'El viaje a España fue muy largo pero divertido.'),
('es', 'A2', 'podróże', 'el aeropuerto', 'lotnisko', 'Llegamos al aeropuerto dos horas antes del vuelo.'),
('es', 'A2', 'podróże', 'el hotel', 'hotel', 'Reservamos una habitación en un hotel cerca de la playa.'),
('es', 'A2', 'podróże', 'la maleta', 'walizka', 'Mi maleta pesa demasiado para el avión.'),
('es', 'A2', 'podróże', 'el pasaporte', 'paszport', 'No puedes viajar al extranjero sin el pasaporte.'),
('es', 'A2', 'podróże', 'el billete', 'bilet', 'Compré un billete de ida y vuelta a Madrid.'),
('es', 'A2', 'podróże', 'la playa', 'plaża', 'En verano vamos a la playa casi todos los días.'),
('es', 'A2', 'podróże', 'el turista', 'turysta', 'El turista pidió ayuda para encontrar el museo.'),
('es', 'A2', 'podróże', 'la reserva', 'rezerwacja', 'Hice una reserva para dos noches en el hotel.'),
('es', 'A2', 'podróże', 'el mapa', 'mapa', 'Usamos un mapa para no perdernos en la ciudad.'),
('es', 'A2', 'podróże', 'la frontera', 'granica', 'Cruzamos la frontera entre Francia y España en coche.'),
('es', 'A2', 'podróże', 'el equipaje', 'bagaż', 'Facturamos el equipaje antes de subir al avión.'),
('es', 'A2', 'podróże', 'la habitación', 'pokój', 'La habitación del hotel tiene vistas al mar.'),
('es', 'A2', 'podróże', 'el destino', 'cel podróży', 'Nuestro destino final es una pequeña isla del sur.'),
('es', 'A2', 'podróże', 'la excursión', 'wycieczka', 'Hicimos una excursión a las montañas el domingo.'),
('es', 'A2', 'podróże', 'el extranjero', 'zagranica (obcokrajowiec)', 'Este verano quiero viajar al extranjero con mis amigos.'),
('es', 'A2', 'podróże', 'la guía', 'przewodnik (osoba/książka)', 'La guía nos explicó la historia del castillo.'),
('es', 'A2', 'podróże', 'el recuerdo', 'pamiątka', 'Compré un recuerdo para mi familia en el mercado.'),
('es', 'A2', 'podróże', 'alojarse', 'zatrzymać się (na nocleg)', 'Vamos a alojarnos en casa de mis primos.'),
('es', 'A2', 'podróże', 'la aventura', 'przygoda', 'El viaje por Sudamérica fue una gran aventura.'),
('es', 'A2', 'podróże', 'la costa', 'wybrzeże', 'La costa del norte es fría pero muy bonita.'),
-- ---------- praca ----------
('es', 'A2', 'praca', 'el trabajo', 'praca', 'Mi trabajo empieza a las nueve de la mañana.'),
('es', 'A2', 'praca', 'la oficina', 'biuro', 'Trabajo en una oficina en el centro de la ciudad.'),
('es', 'A2', 'praca', 'el jefe', 'szef', 'Mi jefe es muy amable con todos los empleados.'),
('es', 'A2', 'praca', 'la reunión', 'spotkanie (zebranie)', 'Tenemos una reunión importante esta tarde.'),
('es', 'A2', 'praca', 'el sueldo', 'pensja', 'Este mes he recibido un buen sueldo.'),
('es', 'A2', 'praca', 'el empleo', 'zatrudnienie (posada)', 'Busca un empleo mejor pagado desde hace meses.'),
('es', 'A2', 'praca', 'la empresa', 'firma', 'La empresa donde trabajo vende ordenadores.'),
('es', 'A2', 'praca', 'el compañero', 'kolega (z pracy)', 'Mi compañero de trabajo me ayuda cada día.'),
('es', 'A2', 'praca', 'el horario', 'grafik (godziny pracy)', 'Mi horario de trabajo es de ocho a cuatro.'),
('es', 'A2', 'praca', 'la entrevista', 'rozmowa kwalifikacyjna', 'Mañana tengo una entrevista para un nuevo trabajo.'),
('es', 'A2', 'praca', 'el contrato', 'umowa', 'Firmé el contrato con la empresa la semana pasada.'),
('es', 'A2', 'praca', 'la tarea', 'zadanie', 'Tengo muchas tareas que terminar antes del viernes.'),
('es', 'A2', 'praca', 'el proyecto', 'projekt', 'Estamos trabajando en un proyecto muy grande.'),
('es', 'A2', 'praca', 'el cliente', 'klient', 'El cliente quiere hablar con el director.'),
('es', 'A2', 'praca', 'la carrera', 'kariera (kierunek studiów)', 'Quiere hacer carrera en una empresa internacional.'),
('es', 'A2', 'praca', 'el ordenador', 'komputer', 'Mi ordenador es muy lento por las mañanas.'),
('es', 'A2', 'praca', 'despedir', 'zwolnić (z pracy)', 'La empresa tuvo que despedir a varios trabajadores.'),
('es', 'A2', 'praca', 'contratar', 'zatrudnić', 'Van a contratar a dos personas nuevas este mes.'),
('es', 'A2', 'praca', 'la experiencia', 'doświadczenie', 'Tengo cinco años de experiencia en ventas.'),
('es', 'A2', 'praca', 'el descanso', 'przerwa (odpoczynek)', 'Hacemos un descanso de veinte minutos a mediodía.'),
('es', 'A2', 'praca', 'la fábrica', 'fabryka', 'Mi padre trabaja en una fábrica de coches.'),
-- ---------- zakupy ----------
('es', 'A2', 'zakupy', 'la tienda', 'sklep', 'Compré esta camisa en una tienda del centro.'),
('es', 'A2', 'zakupy', 'el mercado', 'targ (rynek)', 'Los sábados voy al mercado a comprar fruta.'),
('es', 'A2', 'zakupy', 'el precio', 'cena', 'El precio de este teléfono es demasiado alto.'),
('es', 'A2', 'zakupy', 'la caja', 'kasa', 'Paga en la caja que está al lado de la puerta.'),
('es', 'A2', 'zakupy', 'el dinero', 'pieniądze', 'No llevo suficiente dinero para comprar eso.'),
('es', 'A2', 'zakupy', 'la oferta', 'oferta (promocja)', 'Estos zapatos están en oferta esta semana.'),
('es', 'A2', 'zakupy', 'el descuento', 'zniżka', 'Me hicieron un descuento del veinte por ciento.'),
('es', 'A2', 'zakupy', 'la ropa', 'ubrania', 'Necesito comprar ropa nueva para el invierno.'),
('es', 'A2', 'zakupy', 'el supermercado', 'supermarket', 'Voy al supermercado a comprar leche y pan.'),
('es', 'A2', 'zakupy', 'la bolsa', 'torba', '¿Puede darme una bolsa para la compra, por favor?'),
('es', 'A2', 'zakupy', 'la dependienta', 'sprzedawczyni', 'La dependienta me ayudó a elegir un regalo.'),
('es', 'A2', 'zakupy', 'gastar', 'wydawać (pieniądze)', 'No me gusta gastar mucho dinero en ropa.'),
('es', 'A2', 'zakupy', 'pagar', 'płacić', 'Prefiero pagar con tarjeta y no con dinero.'),
('es', 'A2', 'zakupy', 'barato', 'tani', 'Este restaurante es bueno y muy barato.'),
('es', 'A2', 'zakupy', 'caro', 'drogi', 'El abrigo era muy bonito pero demasiado caro.'),
('es', 'A2', 'zakupy', 'la tarjeta', 'karta (płatnicza)', 'Pagué la comida con la tarjeta de crédito.'),
('es', 'A2', 'zakupy', 'el escaparate', 'witryna sklepowa', 'Vimos un vestido precioso en el escaparate.'),
('es', 'A2', 'zakupy', 'probarse', 'przymierzać', '¿Puedo probarme estos pantalones, por favor?'),
('es', 'A2', 'zakupy', 'la talla', 'rozmiar (ubrania)', '¿Tiene esta camiseta en una talla más grande?'),
('es', 'A2', 'zakupy', 'el recibo', 'paragon', 'Guarda el recibo por si quieres devolver algo.'),
('es', 'A2', 'zakupy', 'el regalo', 'prezent', 'Compré un regalo de cumpleaños para mi hermana.'),
-- ---------- pogoda ----------
('es', 'A2', 'pogoda', 'el tiempo', 'pogoda', '¿Qué tiempo hace hoy en tu ciudad?'),
('es', 'A2', 'pogoda', 'el sol', 'słońce', 'En verano el sol es muy fuerte al mediodía.'),
('es', 'A2', 'pogoda', 'la lluvia', 'deszcz', 'La lluvia no paró en toda la noche.'),
('es', 'A2', 'pogoda', 'la nieve', 'śnieg', 'Los niños juegan en la nieve durante el invierno.'),
('es', 'A2', 'pogoda', 'el viento', 'wiatr', 'Hace mucho viento y no puedo abrir el paraguas.'),
('es', 'A2', 'pogoda', 'la nube', 'chmura', 'El cielo está lleno de nubes grises.'),
('es', 'A2', 'pogoda', 'la tormenta', 'burza', 'Empezó una tormenta con mucho ruido y luz.'),
('es', 'A2', 'pogoda', 'el calor', 'upał (ciepło)', 'En agosto hace mucho calor en el sur.'),
('es', 'A2', 'pogoda', 'el frío', 'zimno', 'Hace tanto frío que necesito otro abrigo.'),
('es', 'A2', 'pogoda', 'el cielo', 'niebo', 'El cielo está azul y no hay ni una nube.'),
('es', 'A2', 'pogoda', 'la temperatura', 'temperatura', 'La temperatura baja mucho por la noche.'),
('es', 'A2', 'pogoda', 'la niebla', 'mgła', 'Con esta niebla es difícil ver la carretera.'),
('es', 'A2', 'pogoda', 'húmedo', 'wilgotny', 'El clima de la costa es muy húmedo en verano.'),
('es', 'A2', 'pogoda', 'seco', 'suchy', 'El verano fue muy seco y casi sin lluvia.'),
('es', 'A2', 'pogoda', 'nublado', 'pochmurny', 'El día está nublado pero no hace frío.'),
('es', 'A2', 'pogoda', 'soleado', 'słoneczny', 'Hoy es un día soleado y muy agradable.'),
('es', 'A2', 'pogoda', 'el paraguas', 'parasol (od deszczu)', 'No olvides el paraguas, va a llover pronto.'),
('es', 'A2', 'pogoda', 'el grado', 'stopień (temperatury)', 'Hoy estamos a treinta grados a la sombra.'),
('es', 'A2', 'pogoda', 'la primavera', 'wiosna', 'En primavera las flores empiezan a crecer.'),
('es', 'A2', 'pogoda', 'el invierno', 'zima', 'En invierno me gusta beber chocolate caliente.'),
('es', 'A2', 'pogoda', 'despejado', 'bezchmurny', 'Por la mañana el cielo estaba despejado.'),
-- ---------- zdrowie ----------
('es', 'A2', 'zdrowie', 'la salud', 'zdrowie', 'Hacer deporte es muy bueno para la salud.'),
('es', 'A2', 'zdrowie', 'el médico', 'lekarz', 'Tengo que ir al médico porque me duele la cabeza.'),
('es', 'A2', 'zdrowie', 'el hospital', 'szpital', 'Llevaron a mi abuelo al hospital por la noche.'),
('es', 'A2', 'zdrowie', 'la enfermedad', 'choroba', 'Es una enfermedad común entre los niños.'),
('es', 'A2', 'zdrowie', 'la medicina', 'lekarstwo (medycyna)', 'El médico me dio una medicina para la tos.'),
('es', 'A2', 'zdrowie', 'el dolor', 'ból', 'Tengo un dolor muy fuerte en la espalda.'),
('es', 'A2', 'zdrowie', 'la fiebre', 'gorączka', 'El niño tiene fiebre y hoy no va al colegio.'),
('es', 'A2', 'zdrowie', 'la tos', 'kaszel', 'Con esta tos no puedo dormir por la noche.'),
('es', 'A2', 'zdrowie', 'el resfriado', 'przeziębienie', 'Cogí un resfriado por salir sin abrigo.'),
('es', 'A2', 'zdrowie', 'la farmacia', 'apteka', 'Compré las pastillas en la farmacia de la esquina.'),
('es', 'A2', 'zdrowie', 'la pastilla', 'tabletka', 'Tomo una pastilla cada mañana para el dolor.'),
('es', 'A2', 'zdrowie', 'el enfermo', 'chory (osoba)', 'El enfermo necesita descansar unos días en casa.'),
('es', 'A2', 'zdrowie', 'la enfermera', 'pielęgniarka', 'La enfermera me puso una inyección en el brazo.'),
('es', 'A2', 'zdrowie', 'sano', 'zdrowy', 'Es importante comer sano y hacer ejercicio.'),
('es', 'A2', 'zdrowie', 'curar', 'leczyć (wyleczyć)', 'Este jarabe ayuda a curar la tos muy rápido.'),
('es', 'A2', 'zdrowie', 'doler', 'boleć', 'Me duelen las piernas después de correr.'),
('es', 'A2', 'zdrowie', 'el cuerpo', 'ciało', 'El deporte es bueno para todo el cuerpo.'),
('es', 'A2', 'zdrowie', 'la cabeza', 'głowa', 'Me duele la cabeza desde esta mañana.'),
('es', 'A2', 'zdrowie', 'el brazo', 'ramię', 'Se rompió el brazo jugando al fútbol.'),
('es', 'A2', 'zdrowie', 'la receta', 'recepta', 'El médico me dio una receta para el antibiótico.'),
('es', 'A2', 'zdrowie', 'cansado', 'zmęczony', 'Estoy muy cansado después de un día largo.'),
-- ---------- czas wolny ----------
('es', 'A2', 'czas wolny', 'el ocio', 'czas wolny (rozrywka)', 'Dedico mi tiempo de ocio a la música y al deporte.'),
('es', 'A2', 'czas wolny', 'la película', 'film', 'Anoche vimos una película muy divertida.'),
('es', 'A2', 'czas wolny', 'el cine', 'kino', 'Vamos al cine el sábado por la tarde.'),
('es', 'A2', 'czas wolny', 'el libro', 'książka', 'Estoy leyendo un libro muy interesante.'),
('es', 'A2', 'czas wolny', 'la música', 'muzyka', 'Me encanta escuchar música mientras cocino.'),
('es', 'A2', 'czas wolny', 'el deporte', 'sport', 'Hago deporte tres veces a la semana.'),
('es', 'A2', 'czas wolny', 'el concierto', 'koncert', 'El concierto de rock empieza a las nueve.'),
('es', 'A2', 'czas wolny', 'el museo', 'muzeum', 'Visitamos un museo de arte moderno.'),
('es', 'A2', 'czas wolny', 'la fiesta', 'impreza (przyjęcie)', 'Vamos a una fiesta de cumpleaños esta noche.'),
('es', 'A2', 'czas wolny', 'el juego', 'gra', 'A los niños les gusta este juego de mesa.'),
('es', 'A2', 'czas wolny', 'bailar', 'tańczyć', 'Nos gusta bailar toda la noche en las fiestas.'),
('es', 'A2', 'czas wolny', 'cantar', 'śpiewać', 'Mi hermana canta muy bien en el coro.'),
('es', 'A2', 'czas wolny', 'leer', 'czytać', 'Me gusta leer un rato antes de dormir.'),
('es', 'A2', 'czas wolny', 'la afición', 'hobby (zainteresowanie)', 'Mi afición favorita es la fotografía.'),
('es', 'A2', 'czas wolny', 'el pasatiempo', 'hobby (zajęcie)', 'Coleccionar sellos es un pasatiempo tranquilo.'),
('es', 'A2', 'czas wolny', 'el teatro', 'teatr', 'Fuimos al teatro a ver una obra clásica.'),
('es', 'A2', 'czas wolny', 'la revista', 'czasopismo', 'Compro una revista de viajes cada mes.'),
('es', 'A2', 'czas wolny', 'el parque', 'park', 'Los domingos paseamos por el parque.'),
('es', 'A2', 'czas wolny', 'la guitarra', 'gitara', 'Estoy aprendiendo a tocar la guitarra.'),
('es', 'A2', 'czas wolny', 'dibujar', 'rysować', 'A mi hijo le encanta dibujar animales.'),
('es', 'A2', 'czas wolny', 'la exposición', 'wystawa', 'Hay una exposición de fotos en el centro.'),
-- ---------- transport ----------
('es', 'A2', 'transport', 'el coche', 'samochód', 'Voy al trabajo en coche todos los días.'),
('es', 'A2', 'transport', 'el autobús', 'autobus', 'El autobús número cinco pasa por mi calle.'),
('es', 'A2', 'transport', 'el tren', 'pociąg', 'El tren a Barcelona sale a las ocho.'),
('es', 'A2', 'transport', 'el avión', 'samolot', 'El avión aterrizó con una hora de retraso.'),
('es', 'A2', 'transport', 'la bicicleta', 'rower', 'Voy a la escuela en bicicleta cuando hace sol.'),
('es', 'A2', 'transport', 'el metro', 'metro', 'El metro es la forma más rápida de moverse.'),
('es', 'A2', 'transport', 'el taxi', 'taksówka', 'Cogimos un taxi porque llovía mucho.'),
('es', 'A2', 'transport', 'la estación', 'dworzec (stacja)', 'Te espero en la estación de tren a las diez.'),
('es', 'A2', 'transport', 'la parada', 'przystanek', 'La parada del autobús está delante de mi casa.'),
('es', 'A2', 'transport', 'el conductor', 'kierowca', 'El conductor del autobús es muy simpático.'),
('es', 'A2', 'transport', 'el barco', 'statek (łódź)', 'Cruzamos el río en un pequeño barco.'),
('es', 'A2', 'transport', 'la carretera', 'droga (szosa)', 'La carretera hacia la montaña es muy estrecha.'),
('es', 'A2', 'transport', 'el vuelo', 'lot', 'El vuelo a Roma dura casi tres horas.'),
('es', 'A2', 'transport', 'conducir', 'prowadzić (pojazd)', 'Aprendí a conducir a los dieciocho años.'),
('es', 'A2', 'transport', 'aparcar', 'parkować', 'Es difícil aparcar el coche en el centro.'),
('es', 'A2', 'transport', 'el semáforo', 'sygnalizacja świetlna', 'Para el coche, el semáforo está en rojo.'),
('es', 'A2', 'transport', 'la gasolina', 'benzyna', 'Tenemos que poner gasolina antes de salir.'),
('es', 'A2', 'transport', 'el asiento', 'siedzenie (miejsce)', 'Mi asiento en el tren está junto a la ventana.'),
('es', 'A2', 'transport', 'el retraso', 'opóźnienie', 'El tren llegó con mucho retraso esta mañana.'),
('es', 'A2', 'transport', 'la moto', 'motocykl', 'Va al trabajo en moto para llegar antes.'),
('es', 'A2', 'transport', 'el puente', 'most', 'Cruzamos el puente para llegar al otro lado.'),
-- ---------- uczucia podstawowe ----------
('es', 'A2', 'uczucia podstawowe', 'la alegría', 'radość', 'Sentí una gran alegría al ver a mi familia.'),
('es', 'A2', 'uczucia podstawowe', 'la tristeza', 'smutek', 'La película me produjo mucha tristeza.'),
('es', 'A2', 'uczucia podstawowe', 'el miedo', 'strach', 'El niño tiene miedo a la oscuridad.'),
('es', 'A2', 'uczucia podstawowe', 'el amor', 'miłość', 'El amor entre ellos dos es muy fuerte.'),
('es', 'A2', 'uczucia podstawowe', 'la felicidad', 'szczęście', 'La felicidad no depende solo del dinero.'),
('es', 'A2', 'uczucia podstawowe', 'el enfado', 'złość', 'No pudo esconder su enfado durante la reunión.'),
('es', 'A2', 'uczucia podstawowe', 'la sorpresa', 'niespodzianka (zaskoczenie)', 'Su visita fue una gran sorpresa para todos.'),
('es', 'A2', 'uczucia podstawowe', 'contento', 'zadowolony', 'Estoy muy contento con mi nuevo trabajo.'),
('es', 'A2', 'uczucia podstawowe', 'triste', 'smutny', 'Se puso triste al leer aquella carta.'),
('es', 'A2', 'uczucia podstawowe', 'feliz', 'szczęśliwy', 'Me siento feliz cuando estoy con mis amigos.'),
('es', 'A2', 'uczucia podstawowe', 'enfadado', 'zły (rozgniewany)', 'Está enfadado porque llegamos muy tarde.'),
('es', 'A2', 'uczucia podstawowe', 'nervioso', 'zdenerwowany', 'Estoy nervioso antes de cada examen.'),
('es', 'A2', 'uczucia podstawowe', 'tranquilo', 'spokojny', 'Después de las vacaciones me siento más tranquilo.'),
('es', 'A2', 'uczucia podstawowe', 'asustado', 'przestraszony', 'El perro parecía asustado por el ruido.'),
('es', 'A2', 'uczucia podstawowe', 'sorprendido', 'zaskoczony', 'Se quedó sorprendido con la noticia.'),
('es', 'A2', 'uczucia podstawowe', 'reír', 'śmiać się', 'No pude parar de reír con sus chistes.'),
('es', 'A2', 'uczucia podstawowe', 'llorar', 'płakać', 'El bebé empezó a llorar en medio de la noche.'),
('es', 'A2', 'uczucia podstawowe', 'el sentimiento', 'uczucie', 'Es difícil explicar este sentimiento con palabras.'),
('es', 'A2', 'uczucia podstawowe', 'la emoción', 'emocja (wzruszenie)', 'Sintió una gran emoción al recibir el premio.'),
('es', 'A2', 'uczucia podstawowe', 'querer', 'kochać (chcieć)', 'Quiero mucho a mis abuelos.'),
('es', 'A2', 'uczucia podstawowe', 'odiar', 'nienawidzić', 'Odio levantarme temprano los lunes.');
