-- ============================================================================
-- Seed: Russian (ru) CEFR A1 vocabulary for Polish-speaking learners
-- Table: vocabulary_words
-- language = 'ru', level = 'A1' for every row.
-- word_en holds the Russian word in Cyrillic (stress not marked).
-- translation_pl holds the Polish translation.
-- example_sentence is a natural A1-level Russian sentence using word_en.
-- Idempotent: existing ru/A1 rows are removed before re-inserting.
-- ============================================================================

delete from vocabulary_words where language = 'ru' and level = 'A1';

insert into vocabulary_words (language, level, category, word_en, translation_pl, example_sentence) values
-- rodzina
('ru', 'A1', 'rodzina', 'семья', 'rodzina', 'Это моя семья.'),
('ru', 'A1', 'rodzina', 'мама', 'mama', 'Моя мама дома.'),
('ru', 'A1', 'rodzina', 'папа', 'tata', 'Мой папа работает.'),
('ru', 'A1', 'rodzina', 'мать', 'matka', 'Моя мать — врач.'),
('ru', 'A1', 'rodzina', 'отец', 'ojciec', 'Мой отец — учитель.'),
('ru', 'A1', 'rodzina', 'брат', 'brat', 'У меня есть брат.'),
('ru', 'A1', 'rodzina', 'сестра', 'siostra', 'Моя сестра — студентка.'),
('ru', 'A1', 'rodzina', 'сын', 'syn', 'Их сын ещё маленький.'),
('ru', 'A1', 'rodzina', 'дочь', 'córka', 'Их дочь очень красивая.'),
('ru', 'A1', 'rodzina', 'бабушка', 'babcia', 'Моя бабушка старая.'),
('ru', 'A1', 'rodzina', 'дедушка', 'dziadek', 'Мой дедушка добрый.'),
('ru', 'A1', 'rodzina', 'родители', 'rodzice', 'Мои родители сейчас дома.'),
('ru', 'A1', 'rodzina', 'дети', 'dzieci', 'У них двое детей.'),
('ru', 'A1', 'rodzina', 'ребёнок', 'dziecko', 'Ребёнок спит.'),
('ru', 'A1', 'rodzina', 'муж', 'mąż', 'Её муж — инженер.'),
('ru', 'A1', 'rodzina', 'жена', 'żona', 'Его жена — учительница.'),
('ru', 'A1', 'rodzina', 'внук', 'wnuk', 'Их внук в школе.'),
('ru', 'A1', 'rodzina', 'внучка', 'wnuczka', 'Их внучка совсем маленькая.'),
-- kolory
('ru', 'A1', 'kolory', 'цвет', 'kolor', 'Какой это цвет?'),
('ru', 'A1', 'kolory', 'красный', 'czerwony', 'У меня красный мяч.'),
('ru', 'A1', 'kolory', 'синий', 'niebieski (granatowy)', 'Небо сегодня синее.'),
('ru', 'A1', 'kolory', 'голубой', 'błękitny (jasnoniebieski)', 'У неё голубые глаза.'),
('ru', 'A1', 'kolory', 'зелёный', 'zielony', 'Трава зелёная.'),
('ru', 'A1', 'kolory', 'жёлтый', 'żółty', 'Солнце жёлтое.'),
('ru', 'A1', 'kolory', 'белый', 'biały', 'Снег белый.'),
('ru', 'A1', 'kolory', 'чёрный', 'czarny', 'У меня чёрный кот.'),
('ru', 'A1', 'kolory', 'серый', 'szary', 'Небо серое и скучное.'),
('ru', 'A1', 'kolory', 'коричневый', 'brązowy', 'У него коричневые ботинки.'),
('ru', 'A1', 'kolory', 'розовый', 'różowy', 'У неё розовое платье.'),
('ru', 'A1', 'kolory', 'оранжевый', 'pomarańczowy', 'Апельсин оранжевый.'),
('ru', 'A1', 'kolory', 'фиолетовый', 'fioletowy', 'Мне нравится фиолетовый цвет.'),
('ru', 'A1', 'kolory', 'светлый', 'jasny', 'У неё светлые волосы.'),
('ru', 'A1', 'kolory', 'тёмный', 'ciemny', 'В комнате тёмный ковёр.'),
('ru', 'A1', 'kolory', 'золотой', 'złoty', 'У неё золотое кольцо.'),
-- liczby
('ru', 'A1', 'liczby', 'ноль', 'zero', 'Ноль плюс один — один.'),
('ru', 'A1', 'liczby', 'один', 'jeden', 'У меня один брат.'),
('ru', 'A1', 'liczby', 'два', 'dwa', 'У меня два кота.'),
('ru', 'A1', 'liczby', 'три', 'trzy', 'Три яблока на столе.'),
('ru', 'A1', 'liczby', 'четыре', 'cztery', 'У неё четыре книги.'),
('ru', 'A1', 'liczby', 'пять', 'pięć', 'Пять минут, пожалуйста.'),
('ru', 'A1', 'liczby', 'шесть', 'sześć', 'Моему сыну шесть лет.'),
('ru', 'A1', 'liczby', 'семь', 'siedem', 'В неделе семь дней.'),
('ru', 'A1', 'liczby', 'восемь', 'osiem', 'Сейчас восемь часов утра.'),
('ru', 'A1', 'liczby', 'девять', 'dziewięć', 'Здесь девять человек.'),
('ru', 'A1', 'liczby', 'десять', 'dziesięć', 'У меня десять пальцев.'),
('ru', 'A1', 'liczby', 'одиннадцать', 'jedenaście', 'Ей одиннадцать лет.'),
('ru', 'A1', 'liczby', 'двенадцать', 'dwanaście', 'В году двенадцать месяцев.'),
('ru', 'A1', 'liczby', 'двадцать', 'dwadzieścia', 'Мне двадцать лет.'),
('ru', 'A1', 'liczby', 'сто', 'sto', 'Сто рублей, пожалуйста.'),
('ru', 'A1', 'liczby', 'тысяча', 'tysiąc', 'Это стоит тысячу рублей.'),
('ru', 'A1', 'liczby', 'первый', 'pierwszy', 'Это мой первый день.'),
('ru', 'A1', 'liczby', 'второй', 'drugi', 'Второй урок трудный.'),
-- jedzenie
('ru', 'A1', 'jedzenie', 'еда', 'jedzenie', 'Еда очень вкусная.'),
('ru', 'A1', 'jedzenie', 'хлеб', 'chleb', 'Утром я ем хлеб.'),
('ru', 'A1', 'jedzenie', 'вода', 'woda', 'Я пью воду.'),
('ru', 'A1', 'jedzenie', 'молоко', 'mleko', 'Дети пьют молоко.'),
('ru', 'A1', 'jedzenie', 'мясо', 'mięso', 'Я люблю мясо.'),
('ru', 'A1', 'jedzenie', 'рыба', 'ryba', 'Рыба лежит на столе.'),
('ru', 'A1', 'jedzenie', 'яблоко', 'jabłko', 'Это красное яблоко.'),
('ru', 'A1', 'jedzenie', 'суп', 'zupa', 'Суп очень горячий.'),
('ru', 'A1', 'jedzenie', 'сыр', 'ser', 'Я люблю сыр.'),
('ru', 'A1', 'jedzenie', 'масло', 'masło', 'Хлеб с маслом.'),
('ru', 'A1', 'jedzenie', 'яйцо', 'jajko', 'Утром я ем яйцо.'),
('ru', 'A1', 'jedzenie', 'чай', 'herbata', 'Я пью чай.'),
('ru', 'A1', 'jedzenie', 'кофе', 'kawa', 'Он пьёт кофе.'),
('ru', 'A1', 'jedzenie', 'сахар', 'cukier', 'Чай без сахара.'),
('ru', 'A1', 'jedzenie', 'соль', 'sól', 'Дай мне соль, пожалуйста.'),
('ru', 'A1', 'jedzenie', 'фрукты', 'owoce', 'Я люблю фрукты.'),
('ru', 'A1', 'jedzenie', 'овощи', 'warzywa', 'Овощи очень полезны.'),
('ru', 'A1', 'jedzenie', 'картофель', 'ziemniak', 'На ужин картофель.'),
-- dom
('ru', 'A1', 'dom', 'дом', 'dom', 'Мой дом большой.'),
('ru', 'A1', 'dom', 'квартира', 'mieszkanie', 'У меня маленькая квартира.'),
('ru', 'A1', 'dom', 'комната', 'pokój', 'Это моя комната.'),
('ru', 'A1', 'dom', 'кухня', 'kuchnia', 'Кухня светлая.'),
('ru', 'A1', 'dom', 'дверь', 'drzwi', 'Дверь открыта.'),
('ru', 'A1', 'dom', 'окно', 'okno', 'Окно большое.'),
('ru', 'A1', 'dom', 'стол', 'stół', 'На столе книга.'),
('ru', 'A1', 'dom', 'стул', 'krzesło', 'Стул стоит у окна.'),
('ru', 'A1', 'dom', 'кровать', 'łóżko', 'Кровать очень удобная.'),
('ru', 'A1', 'dom', 'диван', 'kanapa', 'Диван стоит в комнате.'),
('ru', 'A1', 'dom', 'пол', 'podłoga', 'Пол чистый.'),
('ru', 'A1', 'dom', 'стена', 'ściana', 'Стена белая.'),
('ru', 'A1', 'dom', 'потолок', 'sufit', 'Потолок высокий.'),
('ru', 'A1', 'dom', 'ванная', 'łazienka', 'Ванная маленькая.'),
('ru', 'A1', 'dom', 'шкаф', 'szafa', 'Одежда в шкафу.'),
('ru', 'A1', 'dom', 'лампа', 'lampa', 'Лампа стоит на столе.'),
('ru', 'A1', 'dom', 'ключ', 'klucz', 'Где мой ключ?'),
-- dni tygodnia
('ru', 'A1', 'dni tygodnia', 'понедельник', 'poniedziałek', 'В понедельник я работаю.'),
('ru', 'A1', 'dni tygodnia', 'вторник', 'wtorek', 'Во вторник у меня урок.'),
('ru', 'A1', 'dni tygodnia', 'среда', 'środa', 'В среду я дома.'),
('ru', 'A1', 'dni tygodnia', 'четверг', 'czwartek', 'В четверг я очень занят.'),
('ru', 'A1', 'dni tygodnia', 'пятница', 'piątek', 'В пятницу мы отдыхаем.'),
('ru', 'A1', 'dni tygodnia', 'суббота', 'sobota', 'В субботу я сплю долго.'),
('ru', 'A1', 'dni tygodnia', 'воскресенье', 'niedziela', 'В воскресенье я гуляю.'),
('ru', 'A1', 'dni tygodnia', 'неделя', 'tydzień', 'В неделе семь дней.'),
('ru', 'A1', 'dni tygodnia', 'выходной', 'dzień wolny (weekend)', 'Сегодня выходной.'),
('ru', 'A1', 'dni tygodnia', 'будни', 'dni robocze', 'В будни я всегда работаю.'),
-- podstawowe czasowniki
('ru', 'A1', 'podstawowe czasowniki', 'быть', 'być', 'Я хочу быть врачом.'),
('ru', 'A1', 'podstawowe czasowniki', 'иметь', 'mieć', 'Хорошо иметь друга.'),
('ru', 'A1', 'podstawowe czasowniki', 'делать', 'robić', 'Что ты делаешь?'),
('ru', 'A1', 'podstawowe czasowniki', 'говорить', 'mówić', 'Я говорю по-русски.'),
('ru', 'A1', 'podstawowe czasowniki', 'читать', 'czytać', 'Я читаю книгу.'),
('ru', 'A1', 'podstawowe czasowniki', 'писать', 'pisać', 'Я пишу письмо.'),
('ru', 'A1', 'podstawowe czasowniki', 'работать', 'pracować', 'Я работаю в офисе.'),
('ru', 'A1', 'podstawowe czasowniki', 'жить', 'mieszkać (żyć)', 'Я живу в Москве.'),
('ru', 'A1', 'podstawowe czasowniki', 'есть', 'jeść', 'Я ем суп.'),
('ru', 'A1', 'podstawowe czasowniki', 'пить', 'pić', 'Я пью воду.'),
('ru', 'A1', 'podstawowe czasowniki', 'идти', 'iść', 'Я иду домой.'),
('ru', 'A1', 'podstawowe czasowniki', 'ехать', 'jechać', 'Я еду в город.'),
('ru', 'A1', 'podstawowe czasowniki', 'знать', 'wiedzieć (znać)', 'Я знаю это слово.'),
('ru', 'A1', 'podstawowe czasowniki', 'хотеть', 'chcieć', 'Я хочу спать.'),
('ru', 'A1', 'podstawowe czasowniki', 'любить', 'lubić (kochać)', 'Я люблю тебя.'),
('ru', 'A1', 'podstawowe czasowniki', 'видеть', 'widzieć', 'Я вижу дом.'),
('ru', 'A1', 'podstawowe czasowniki', 'слушать', 'słuchać', 'Я слушаю музыку.'),
('ru', 'A1', 'podstawowe czasowniki', 'спать', 'spać', 'Ночью я сплю.'),
-- ubrania
('ru', 'A1', 'ubrania', 'одежда', 'ubranie', 'Одежда лежит в шкафу.'),
('ru', 'A1', 'ubrania', 'рубашка', 'koszula', 'У меня белая рубашка.'),
('ru', 'A1', 'ubrania', 'брюки', 'spodnie', 'Брюки чёрные.'),
('ru', 'A1', 'ubrania', 'платье', 'sukienka', 'Какое красивое платье!'),
('ru', 'A1', 'ubrania', 'юбка', 'spódnica', 'Юбка короткая.'),
('ru', 'A1', 'ubrania', 'куртка', 'kurtka', 'Куртка очень тёплая.'),
('ru', 'A1', 'ubrania', 'пальто', 'płaszcz', 'Зимой я ношу пальто.'),
('ru', 'A1', 'ubrania', 'свитер', 'sweter', 'Свитер тёплый.'),
('ru', 'A1', 'ubrania', 'футболка', 'koszulka (t-shirt)', 'Летом я ношу футболку.'),
('ru', 'A1', 'ubrania', 'джинсы', 'dżinsy', 'Мои джинсы синие.'),
('ru', 'A1', 'ubrania', 'носки', 'skarpetki', 'Носки белые.'),
('ru', 'A1', 'ubrania', 'обувь', 'obuwie', 'Обувь стоит у двери.'),
('ru', 'A1', 'ubrania', 'ботинки', 'buty', 'Ботинки коричневые.'),
('ru', 'A1', 'ubrania', 'туфли', 'pantofle (buty eleganckie)', 'Туфли совсем новые.'),
('ru', 'A1', 'ubrania', 'шапка', 'czapka', 'Зимой я ношу шапку.'),
('ru', 'A1', 'ubrania', 'шарф', 'szalik', 'Шарф красный.'),
('ru', 'A1', 'ubrania', 'перчатки', 'rękawiczki', 'Перчатки тёплые.'),
-- zwierzęta
('ru', 'A1', 'zwierzęta', 'животное', 'zwierzę', 'Это дикое животное.'),
('ru', 'A1', 'zwierzęta', 'собака', 'pies', 'У меня есть собака.'),
('ru', 'A1', 'zwierzęta', 'кошка', 'kot (kotka)', 'Кошка спит на диване.'),
('ru', 'A1', 'zwierzęta', 'кот', 'kot (samiec)', 'Мой кот чёрный.'),
('ru', 'A1', 'zwierzęta', 'лошадь', 'koń', 'Лошадь бежит быстро.'),
('ru', 'A1', 'zwierzęta', 'корова', 'krowa', 'Корова даёт молоко.'),
('ru', 'A1', 'zwierzęta', 'свинья', 'świnia', 'Свинья в поле.'),
('ru', 'A1', 'zwierzęta', 'курица', 'kura (kurczak)', 'Курица во дворе.'),
('ru', 'A1', 'zwierzęta', 'птица', 'ptak', 'Птица поёт.'),
('ru', 'A1', 'zwierzęta', 'утка', 'kaczka', 'Утка плавает на озере.'),
('ru', 'A1', 'zwierzęta', 'коза', 'koza', 'Коза ест траву.'),
('ru', 'A1', 'zwierzęta', 'овца', 'owca', 'Овца белая.'),
('ru', 'A1', 'zwierzęta', 'кролик', 'królik', 'Кролик маленький.'),
('ru', 'A1', 'zwierzęta', 'мышь', 'mysz', 'Мышь быстрая.'),
('ru', 'A1', 'zwierzęta', 'медведь', 'niedźwiedź', 'Медведь большой.'),
('ru', 'A1', 'zwierzęta', 'волк', 'wilk', 'Волк живёт в лесу.'),
('ru', 'A1', 'zwierzęta', 'лиса', 'lis', 'Лиса рыжая.'),
('ru', 'A1', 'zwierzęta', 'слон', 'słoń', 'Слон очень большой.'),
-- czas/godziny
('ru', 'A1', 'czas/godziny', 'время', 'czas', 'Сколько сейчас времени?'),
('ru', 'A1', 'czas/godziny', 'час', 'godzina', 'Один час — шестьдесят минут.'),
('ru', 'A1', 'czas/godziny', 'минута', 'minuta', 'Подожди одну минуту.'),
('ru', 'A1', 'czas/godziny', 'секунда', 'sekunda', 'Одна секунда — это очень мало.'),
('ru', 'A1', 'czas/godziny', 'день', 'dzień', 'Какой хороший день!'),
('ru', 'A1', 'czas/godziny', 'ночь', 'noc', 'Спокойной ночи!'),
('ru', 'A1', 'czas/godziny', 'утро', 'ranek (rano)', 'Доброе утро!'),
('ru', 'A1', 'czas/godziny', 'вечер', 'wieczór', 'Добрый вечер!'),
('ru', 'A1', 'czas/godziny', 'год', 'rok', 'С Новым годом!'),
('ru', 'A1', 'czas/godziny', 'месяц', 'miesiąc', 'В месяце тридцать дней.'),
('ru', 'A1', 'czas/godziny', 'сегодня', 'dzisiaj', 'Сегодня хорошая погода.'),
('ru', 'A1', 'czas/godziny', 'завтра', 'jutro', 'Завтра я работаю.'),
('ru', 'A1', 'czas/godziny', 'вчера', 'wczoraj', 'Вчера был дождь.'),
('ru', 'A1', 'czas/godziny', 'сейчас', 'teraz', 'Сейчас три часа.'),
('ru', 'A1', 'czas/godziny', 'рано', 'wcześnie', 'Утром я встаю рано.'),
('ru', 'A1', 'czas/godziny', 'поздно', 'późno', 'Уже очень поздно.'),
('ru', 'A1', 'czas/godziny', 'полдень', 'południe', 'Сейчас полдень.'),
('ru', 'A1', 'czas/godziny', 'полночь', 'północ', 'Сейчас полночь.');
