-- ============================================================================
-- supabase/seed/geografia/01_topics.sql
-- The 23 CKE "zakres rozszerzony" geography sections (geo_topics). Mirrors
-- lib/geografia/topics.ts GEO_TOPICS exactly — keep both in sync.
--
-- Idempotent: deletes by slug first. Run this BEFORE 02_exercises.sql (it
-- looks up topic_id via `(select id from geo_topics where slug = '...')`).
-- ============================================================================

delete from geo_topics where slug in (
  'zrodla-informacji-geograficznej', 'ziemia-we-wszechswiecie', 'atmosfera', 'hydrosfera', 'litosfera',
  'pedosfera-i-biosfera', 'podzial-polityczny-i-rozwoj-spoleczno-gospodarczy', 'demografia-i-osadnictwo',
  'uwarunkowania-gospodarki-swiatowej', 'rolnictwo-lesnictwo-rybactwo', 'przemysl', 'uslugi',
  'czlowiek-a-srodowisko', 'srodowisko-przyrodnicze-polski', 'spoleczenstwo-i-gospodarka-polski',
  'morze-baltyckie', 'strefowosc-przyrodnicza', 'problemy-srodowiskowe-swiata',
  'uwarunkowania-przyrodnicze-gospodarki', 'problemy-polityczne-swiata', 'problemy-spoleczne-swiata',
  'jakosc-zycia-na-swiecie', 'problemy-gospodarcze-swiata'
);

insert into geo_topics (cke_number, slug, title, description, order_index) values
  ('I', 'zrodla-informacji-geograficznej',
   'Źródła informacji geograficznej, technologie geoinformacyjne oraz metody prezentacji danych przestrzennych',
   'Mapa i jej elementy, skala, siatka geograficzna, GPS/GIS, teledetekcja, interpretacja map tematycznych, wykresów, danych statystycznych i zdjęć satelitarnych.',
   1),
  ('II', 'ziemia-we-wszechswiecie', 'Ziemia we Wszechświecie',
   'Ruch obrotowy i obiegowy Ziemi oraz ich następstwa (strefy czasowe, pory roku, oświetlenie Ziemi), Układ Słoneczny, kształt i wymiary Ziemi.',
   2),
  ('III', 'atmosfera', 'Atmosfera',
   'Budowa i skład atmosfery, bilans radiacyjny, krążenie powietrza, masy powietrza i fronty atmosferyczne, strefy klimatyczne, pogoda a klimat, ekstremalne zjawiska pogodowe.',
   3),
  ('IV', 'hydrosfera', 'Hydrosfera',
   'Krążenie wody w przyrodzie, wody oceaniczne (prądy morskie, pływy), wody śródlądowe (rzeki, jeziora, lodowce, wody podziemne), zasoby wody i ich zagrożenia.',
   4),
  ('V', 'litosfera', 'Litosfera',
   'Budowa wnętrza Ziemi, tektonika płyt, procesy wewnętrzne (wulkanizm, trzęsienia ziemi, ruchy górotwórcze) i zewnętrzne (wietrzenie, erozja, rzeźbotwórcza działalność lodowców, rzek, wiatru, morza), skały.',
   5),
  ('VI', 'pedosfera-i-biosfera', 'Pedosfera i biosfera',
   'Czynniki glebotwórcze i typy gleb, strefowość gleb, formacje roślinne świata, zależności klimat-gleba-roślinność-fauna, ochrona przyrody.',
   6),
  ('VII', 'podzial-polityczny-i-rozwoj-spoleczno-gospodarczy',
   'Podział polityczny i zróżnicowanie poziomu rozwoju społeczno-gospodarczego świata',
   'Mapa polityczna świata, formy ustrojowe państw, ugrupowania integracyjne, mierniki rozwoju (PKB, HDI), podział na kraje wysoko i słabo rozwinięte.',
   7),
  ('VIII', 'demografia-i-osadnictwo', 'Przemiany struktur demograficznych i społecznych oraz procesy osadnicze',
   'Rozmieszczenie ludności, przyrost naturalny i rzeczywisty, migracje, struktura wieku i płci, model przejścia demograficznego, urbanizacja, sieć osadnicza.',
   8),
  ('IX', 'uwarunkowania-gospodarki-swiatowej', 'Uwarunkowania rozwoju gospodarki światowej',
   'Zasoby naturalne i ich wykorzystanie, czynniki lokalizacji działalności gospodarczej, globalizacja, korporacje transnarodowe, handel międzynarodowy.',
   9),
  ('X', 'rolnictwo-lesnictwo-rybactwo', 'Rolnictwo, leśnictwo i rybactwo',
   'Warunki rozwoju rolnictwa, typy rolnictwa na świecie, struktura użytkowania ziemi, leśnictwo, rybołówstwo morskie i akwakultura.',
   10),
  ('XI', 'przemysl', 'Przemysł',
   'Czynniki lokalizacji przemysłu, przemiany strukturalne przemysłu na świecie, okręgi przemysłowe, nowoczesne technologie i przemysł high-tech.',
   11),
  ('XII', 'uslugi', 'Usługi',
   'Struktura i zróżnicowanie usług, transport, turystyka, usługi finansowe i informacyjne, handel.',
   12),
  ('XIII', 'czlowiek-a-srodowisko', 'Człowiek a środowisko geograficzne – konflikty interesów',
   'Antropopresja, degradacja środowiska, zrównoważony rozwój, konflikty w wykorzystaniu zasobów i przestrzeni.',
   13),
  ('XIV', 'srodowisko-przyrodnicze-polski', 'Regionalne zróżnicowanie środowiska przyrodniczego Polski',
   'Ukształtowanie powierzchni, budowa geologiczna, klimat, wody, gleby i szata roślinna Polski w ujęciu regionalnym, krainy geograficzne.',
   14),
  ('XV', 'spoleczenstwo-i-gospodarka-polski', 'Społeczeństwo i gospodarka Polski',
   'Struktura demograficzna i społeczna Polski, sieć osadnicza, rolnictwo, przemysł i usługi w Polsce, zróżnicowanie regionalne rozwoju.',
   15),
  ('XVI', 'morze-baltyckie', 'Morze Bałtyckie i gospodarka morska Polski',
   'Cechy fizycznogeograficzne Bałtyku, porty i żegluga, gospodarka morska Polski, zagrożenia środowiska Morza Bałtyckiego.',
   16),
  ('XVII', 'strefowosc-przyrodnicza', 'Strefowość środowiska przyrodniczego na Ziemi',
   'Strefy klimatyczno-roślinno-glebowe świata, astrefowe zróżnicowanie środowiska (piętrowość górska, wpływ prądów morskich i kontynentalizmu).',
   17),
  ('XVIII', 'problemy-srodowiskowe-swiata', 'Problemy środowiskowe współczesnego świata',
   'Zmiany klimatu, efekt cieplarniany, dziura ozonowa, pustynnienie, wylesianie, zanieczyszczenie wód i atmosfery, utrata bioróżnorodności.',
   18),
  ('XIX', 'uwarunkowania-przyrodnicze-gospodarki', 'Uwarunkowania przyrodnicze gospodarczej działalności człowieka',
   'Wpływ rzeźby terenu, klimatu, wód i zasobów naturalnych na rozmieszczenie rolnictwa, przemysłu, osadnictwa i turystyki w wybranych regionach świata.',
   19),
  ('XX', 'problemy-polityczne-swiata', 'Problemy polityczne współczesnego świata',
   'Konflikty zbrojne i ich podłoże geograficzne, terroryzm, spory graniczne i terytorialne, państwa upadłe, uchodźstwo.',
   20),
  ('XXI', 'problemy-spoleczne-swiata', 'Wybrane problemy społeczne współczesnego świata',
   'Głód i niedożywienie, dostęp do wody pitnej, ubóstwo, nierówności społeczne, starzenie się społeczeństw, epidemie i ich uwarunkowania geograficzne.',
   21),
  ('XXII', 'jakosc-zycia-na-swiecie', 'Zróżnicowanie jakości życia człowieka w wybranych regionach i krajach świata',
   'Wskaźniki jakości życia (HDI, dostęp do edukacji i opieki zdrowotnej), kontrasty rozwojowe między regionami świata, studia przypadków wybranych krajów.',
   22),
  ('XXIII', 'problemy-gospodarcze-swiata', 'Problemy gospodarcze współczesnego świata',
   'Zadłużenie państw, kryzysy gospodarcze, nierównomierny rozwój gospodarczy, transformacja gospodarek postsocjalistycznych, gospodarka oparta na wiedzy.',
   23);
